### ISSUE TITLE
OpenRouter breaks voice

### ISSUE THREAD

**Issue by skorokithakis** [paul-gauthier/aider#902] opened 2024-07-20 15:17 UTC
### Issue

If I use OpenRouter, the `/voice` command breaks, presumably because it uses the OpenRouter API base.

### Version and model info

aider 0.45.1

**Comment by floogy** [comment] 2024-07-22 06:29
Unable to reproduce. I'm using:

Aider v0.45.1
Models: openrouter/anthropic/claude-3.5-sonnet with diff edit format, weak model openrouter/deepseek/deepseek-coder

/voice is working fine here. 

I assume you A/B tested and it works when you switch models? If so, please provide the chat logs.

**Comment by skorokithakis** [comment] 2024-07-22 07:28
Yes I did, it was working fine without the API base and breaking with it. I will try to reproduce again and post everything here.

**Comment by paul-gauthier** [comment] 2024-07-22 12:41
Thanks for trying aider and filing this issue.

How you are you configuring aider to use openrouter? If you do it per the docs, it should not affect `/voice`.

https://aider.chat/docs/llms/openrouter.html

**Comment by paul-gauthier** [comment] 2024-07-22 12:59
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Closed by paul-gauthier** 2024-07-22 12:59 UTC
Labels: question
