### ISSUE TITLE
Changes not applied to file when using gpt-3.5-turbo

### ISSUE THREAD

**Issue by tiktuk** [paul-gauthier/aider#8] opened 2023-05-29 10:41 UTC
Hi, when I use aider, response is printed to the terminal but not applied to the file like described and shown in the screencasts. I don't have GPT-4 access yes, though, so am running with the `-3` flag.

Thanks for doing this, eager to use it :) .

**Comment by paul-gauthier** [comment] 2023-05-29 13:53
Thanks for trying aider!

You are probably correct that the issue is caused by using gpt-3.5-turbo. It doesn't following instructions well, and often fails to  format code in a way that aider expects.

Is it outputting "edit blocks" that look like the example in the prompts?
https://github.com/paul-gauthier/aider/blob/82cc64eb6f4bd1006bf55b94890a76c5db1576b8/aider/prompts.py#L18-L28

If not, then aider won't be able to parse out the edit and apply to the file.

**Comment by tiktuk** [comment] 2023-05-29 22:23
No, it's just outputting the entire file, with its changes. It would be nice if there was a command like `/replace` or `/overwrite` that would simply replace the file with that output. Because the answer is good, even though it's gpt-3.5-turbo.

**Comment by paul-gauthier** [comment] 2023-05-30 18:23
Yes, it would be nice for aider to support some basic functionality with gpt-3.5-turbo. That model is quite limited in what it can do though. With only 4k context window and the need to read and write the entire code that is being modified... you can only work on small pieces of code with it. 

I'll definitely think some more about this and try and find a good approach to adding support for 3.5.

Thanks again for the feedback.

**Comment by paul-gauthier** [comment] 2023-06-10 13:37
I'm going to close this for now. Feel free to reopen or make a new issue if you have problems or questions about gpt-3.5-turbo support.

**Closed by paul-gauthier** 2023-06-10 13:37 UTC
