### ISSUE TITLE
Uncaught UnicodeEncodeError in io.py line 624

### ISSUE THREAD

**Issue by 15315805505** [paul-gauthier/aider#1663] opened 2024-09-23 06:53 UTC
Aider version: 0.57.1
Python version: 3.12.6
Platform: Windows-10-10.0.19045-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.46.1.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 709, in main
    coder.run()
  File "base_coder.py", line 722, in run
    user_message = self.get_input()
                   ^^^^^^^^^^^^^^^^
  File "base_coder.py", line 735, in get_input
    return self.io.get_input(
           ^^^^^^^^^^^^^^^^^^
  File "io.py", line 380, in get_input
    self.user_input(inp)
  File "io.py", line 425, in user_input
    self.append_chat_history(hist, linebreak=True)
  File "io.py", line 624, in append_chat_history
    f.write(text)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc9f' in position 11: surrogates not allowed

```

**Comment by fry69** [comment] 2024-09-23 06:59
Duplicate of #1636

**Closed by fry69** 2024-09-23 06:59 UTC
