### ISSUE TITLE
Remove /help commands from chat history

### ISSUE THREAD

**Issue by ErykCh** [paul-gauthier/aider#857] opened 2024-07-14 11:30 UTC
### Issue

I just wanted to check /help function to ask questions. After two questions I checked /tokens and what I saw:

![image](https://github.com/user-attachments/assets/0a40cb7c-7e58-443c-8f14-0fe758e4f9f1)

I think responses from /help shouldn't be inserted to chat history.

### Version and model info

Aider v0.43.5-dev
Models: openrouter/anthropic/claude-3.5-sonnet with diff edit format, weak model openrouter/anthropic/claude-3-haiku
Git repo: .git with 96 files
Repo-map: using 2028 tokens
Added .aider.memory.md to the chat.

**Comment by jginstitute** [comment] 2024-07-21 16:23
> Leaving the help info in the history is intentional, so you can ask followup questions. You can use `/clear` to wipe the chat history.

Perhaps a reasonable compromise would be to ask the user if they want the /help response added to the chat history (Y/N). Alternatively, maintaining a separate "help chat history" could be an option.

The issue is that most users don't expect to carry forward and pay for the /help history tokens, although they do see the value in retaining chat history during the development process. Currently, knowledgeable users face a dilemma: either lose all their chat history to avoid paying for the /help results, avoid asking for help altogether, or postpone asking for help until they can use /clear.

For those unaware of this behavior, the situation is even worse. They might eventually realize that their chat history has inflated, causing them to pay for extra tokens without understanding why or when this started.

**Comment by paul-gauthier** [comment] 2024-07-27 10:49
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Closed by paul-gauthier** 2024-07-27 10:49 UTC
Labels: question

**Comment by damiencorpataux** [comment] 2024-12-23 21:18
A workaround is to run a separate aider for /help purposes
