### ISSUE TITLE
NixPackages Support

### ISSUE THREAD

**Issue by unchainedio** [paul-gauthier/aider#782] opened 2024-07-03 04:47 UTC
### Issue

HI, alot more people now use nix packages.  i myself am using nixos, installing python dependencies is a pain in nixos.  please package this awesome app as a package that can just be installed on Nix.

### Version and model info

Nix packages so we can just install

pkgs.aider in our config and have it setup

**Comment by paul-gauthier** [comment] 2024-07-03 14:16
Thanks for trying aider and filing this issue.

This looks like a duplicate of #544, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-07-03 14:16 UTC
