### ISSUE TITLE
Uncaught APIError in utils.py line 6841

### ISSUE THREAD

**Issue by mike-courian** [paul-gauthier/aider#1406] opened 2024-09-07 09:36 UTC
Aider version: 0.55.0
Python version: 3.12.2
Platform: macOS-14.3.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.3.0 (64bit)
Git version: git version 2.39.3 (Apple Git-146)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "openai.py", line 1033, in completion
    raise e
  File "openai.py", line 959, in completion
    stringified_response = response.model_dump()
                           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'model_dump'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1345, in completion
    raise e
  File "main.py", line 1318, in completion
    response = openai_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "openai.py", line 1041, in completion
    raise OpenAIError(status_code=500, message=traceback.format_exc())
litellm.llms.openai.OpenAIError: Traceback (most recent call last):
  File "openai.py", line 1033, in completion
    raise e
  File "openai.py", line 959, in completion
    stringified_response = response.model_dump()
                           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'model_dump'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 694, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1183, in send_message
    saved_message = self.auto_commit(edited)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1863, in auto_commit
    res = self.repo.commit(fnames=edited, context=context, aider_edits=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 101, in commit
    commit_message = self.get_commit_message(diffs, context)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 186, in get_commit_message
    commit_message = simple_send_with_retries(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sendchat.py", line 44, in wrapper
    return decorated_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "sendchat.py", line 106, in simple_send_with_retries
    _hash, response = send_completion(**kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sendchat.py", line 86, in send_completion
    res = litellm.completion(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "utils.py", line 1078, in wrapper
    raise e
  File "utils.py", line 966, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 2766, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "utils.py", line 8438, in exception_type
    raise e
  File "utils.py", line 6841, in exception_type
    raise APIError(
litellm.exceptions.APIError: litellm.APIError: APIError: OpenAIException - Traceback (most recent call last):
  File "openai.py", line 1033, in completion
    raise e
  File "openai.py", line 959, in completion
    stringified_response = response.model_dump()
                           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'model_dump'


```

**Comment by paul-gauthier** [comment] 2024-09-09 20:24
Thanks for trying aider and filing this issue.

What model were you using when this happened?

**Comment by mike-courian** [comment] 2024-09-09 23:15
Hi Paul,

I'm a non-developer who is slowly being able to write more and more code using LLM's (so forgive any inaccuracies in this description below). Thanks heaps for responding to this (so grateful for all the work you do on Aider!)

I'm using a custom setup with a private model that I call locally. The setup is quite convoluted and an edge case:

1. Aider sends requests to a fixed Ngrok URL to tunnel into my localhost.
2. The Aider API request is mapped to fit the request format required for my private model API and then sent off.
3. The response is then passed back through and streamed to Aider.

Essentially, it's like a "man-in-the-middle" API setup. The initial part of the process in Aider works perfectly (as if it was from a major provider's API), and all the code gets written as expected. However, when it reaches the stage of making the git commit, or something at the end of the Aider sequence of steps that is too advanced for me to understand, it gets caught in a loop of wanting to 'model_dump', which is missing from the response object.

<AI generated>
I think the issue stems from my custom API setup not providing a response object with a `model_dump()` method as Aider expects. I wonder if a small change in Aider could make it more robust for non-standard API responses (eg. implementing a function that safely handles various response types could prevent this error for other custom setups as well.)

I'll also plan to implement a wrapper for my custom API response to try and resolve it on my end.
</AI generated>

Let me know if you need any additional information if you were going to make any adjustments to how Aider works.

Thanks again!

**Comment by paul-gauthier** [comment] 2024-09-09 23:40
This does seem likely to be caused by your custom api setup. Unfortunately it would be very difficult for me to help debug it. 


I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Closed** 2024-09-09 23:40 UTC
Labels: question
