### ISSUE TITLE
Ask permission to edit files

### ISSUE THREAD

**Issue by generalsvr** [paul-gauthier/aider#1184] opened 2024-08-26 13:53 UTC
### Issue

Hello, how can I make LLM in /code mode to ask every time my permission to edit files? For example, LLM generated a solution, and then asked: 

Apply changes to {file1} {file2}? Y/n

### Version and model info

Aider v0.52.1

**Comment by paul-gauthier** [comment] 2024-08-26 21:45
Thanks for trying aider and filing this issue.

This looks like a duplicate of #649, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-08-26 21:45 UTC
