### ISSUE TITLE
Cmd('git') failed due to: exit code(129)

### ISSUE THREAD

**Issue by SShadowS** [paul-gauthier/aider#1447] opened 2024-09-09 13:52 UTC
### Issue

Error on commit:
Cmd('git') failed due to: exit code(129)
  cmdline: git diff --cached --abbrev=40 --full-index --raw -- src\main.ts
  stderr: 'error: unknown option `cached'
![image](https://github.com/user-attachments/assets/c7057207-b18d-4820-9c22-5a9c5f01c334)

### Version and model info

Platform: Windows (PowerShell 7.4.5)
GIT: git version 2.46.0.windows.1

Aider v0.55.1.dev81+gcee34861
Main model: claude-3-5-sonnet-20240620 with diff edit format, prompt cache, infinite output
Weak model: claude-3-haiku-20240307

**Comment by SShadowS** [comment] 2024-09-09 14:16
I found the issue: a new repo clone wasn't flagged as safe.

**Comment by paul-gauthier** [comment] 2024-09-09 21:14
Thanks for trying aider and filing this issue.

For aider, you'll need to use a git that supports --cached. It's a pretty basic option.

Not sure what you mean by the "new repo clone wasn't flagged as safe"?

**Comment by SShadowS** [comment] 2024-09-09 21:39
git only shows the command valid in the given context. So as the repo wasn't set to save yet, it reported that --cached wasn't available.
After I added the folder, --cached showed up as possible.
```
git diff --cached = ERROR
git config --global --add safe.directory F:/GitHub/my-project
git diff --cached = OK
```

I had just clone the repo. Added and started venv, installed and started Aider. Then the bug came.

**Comment by paul-gauthier** [comment] 2024-09-11 15:37
Any idea why `git diff --cached` would fail when git doesn't consider the directory safe?

**Comment by haal-laah** [comment] 2024-09-20 09:34
I can confirm that `git config --global --add safe.directory F:/GitHub/my-project` fixed this super annoying issue for me. Thank you!

**Comment by paul-gauthier** [comment] 2024-09-20 19:04
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Closed by paul-gauthier** 2024-09-20 19:04 UTC
Labels: question

**Comment by pe-chile** [comment] 2024-10-24 15:37
> git only shows the command valid in the given context. So as the repo wasn't set to save yet, it reported that --cached wasn't available. After I added the folder, --cached showed up as possible.
> 
> ```
> git diff --cached = ERROR
> git config --global --add safe.directory F:/GitHub/my-project
> git diff --cached = OK
> ```
> 
> I had just clone the repo. Added and started venv, installed and started Aider. Then the bug came.

Thanks @SShadowS for sharing this!!! I was going nuts trying to figure out what was going on. 

@paul-gauthier thanks for building aider! It's an incredible tool! I am using it in docker. The service looks like this in my docker-compose.yml:

```
  aider:
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    volumes:
      - ./.aider:/app
      - ./src/my-git-repo:/app/repo
    image: paulgauthier/aider-full
```
So marking the git repository solves the problem inside the docker container

```
git config --global --add safe.directory /app/repo
```

It might be that a new repo created by aider has no issues. Maybe it only applies repos not created by aider. Anyways, the above git command gets rid of this:

```
Cmd('git') failed due to: exit code(129)
  cmdline: git diff --cached --abbrev=40 --full-index --raw -- ###PATH/FILE AIDER IS EDITING GOES HERE###
  stderr: 'error: unknown option `cached'
usage: git diff --no-index [<options>] <path> <path>
```
