### ISSUE TITLE
Uncaught AttributeError in sendchat.py line 30

### ISSUE THREAD

**Issue by adamb** [paul-gauthier/aider#1645] opened 2024-09-22 16:19 UTC
Just upgraded.   Added my wrangler.toml and my src/api/signup/+server.js files. The prompt was: 

log the email and tokens in the signup api.  use the email as the key and the token as the value.

Aider version: 0.56.0
Python version: 3.10.9
Platform: macOS-14.6.1-x86_64-i386-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.44.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 698, in main
    return 1
  File "base_coder.py", line 735, in run
    return self.io.get_input(
  File "base_coder.py", line 778, in run_one
    def check_for_urls(self, inp):
  File "base_coder.py", line 1202, in send_message
  File "base_coder.py", line 1885, in auto_commit
    self.io.tool_error(f"Unable to commit: {str(err)}")
  File "repo.py", line 102, in commit
    commit_message = self.get_commit_message(diffs, context)
  File "repo.py", line 187, in get_commit_message
    commit_message = simple_send_with_retries(
  File "sendchat.py", line 38, in wrapper
    retry_exceptions(),
  File "sendchat.py", line 30, in retry_exceptions
    litellm.llms.anthropic.chat.AnthropicError,
AttributeError: module 'litellm.llms.anthropic' has no attribute 'AnthropicError'

```

**Comment by fry69** [comment] 2024-09-22 16:36
Thank you for filing this issue.

The fix is in the latest version (`0.57.1`), please update aider with
```
aider --upgrade
```

**Comment by paul-gauthier** [comment] 2024-09-22 18:12
Thanks for trying aider and filing this issue.

This looks like a duplicate of #1278. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-09-22 18:12 UTC
