### ISSUE TITLE
Is GPT-4 smarter then GPT-4 Turbo? Can we combine big context window of GPT-4 Turbo with smartness of GPT-4 ?

### ISSUE THREAD

**Issue by gwpl** [paul-gauthier/aider#382] opened 2023-11-30 11:15 UTC
Seeing :

* https://github.com/paul-gauthier/aider/issues/343

may seem like GPT-4 is "smarter" then GPT-4 Turbo.

However has context window limitations (and not everyone access to GPT-4 32k context window version).

I wonder if it would be possible for bigger repositories/adding more file context to combine power of both?

Example ideas:

* whenever context allows use GPT-4 otherwise if too big use GPT-4 Turbo
* for big contexts if GPT-4  Turbo fails, to request it to prepare all required data to perform task in certain length limit and then forward produced shorter "summary" into GPT-4 .
* I am sure everyone will  have more ideas , given e.g. https://aider.chat/docs/repomap.html .

**Comment by paul-gauthier** [comment] 2024-01-22 21:57
Duplicate of #203 .

**Closed by paul-gauthier** 2024-01-22 21:57 UTC
