### ISSUE TITLE
Aider terminal freezes after input of space character

### ISSUE THREAD

**Issue by crypticalcode** [paul-gauthier/aider#286] opened 2023-10-19 21:03 UTC
Hi,
i installed aider on my system using windows 11, vscode and anaconda. When i write something to the chat, the terminal freezes after entering a space character. This was reproducable with cmd and powershell. Voice input did work. 

I added a screenshot. Here the terminal is unresponsive and does not recover. This happend everytime i tried to give an input (longer than one word).

<img width="842" alt="image" src="https://github.com/paul-gauthier/aider/assets/19348829/cd88d95b-16f0-49c7-8ffa-2673019ee2b8">

Can someone help me with this issue? What additional information can i provide?

Thanks a lot!

**Comment by paul-gauthier** [comment] 2023-10-19 22:25
Thanks for trying aider and reporting this issue. I haven't seen anything like this before.

How large is the git repo you're running aider inside? What does aider output if you use the `/ls` command in the chat?

If you run aider outside of VS Code, just in a normal terminal do you have the same problem?

What if you run aider in an empty directory that doesn't have a git repo?

**Comment by paul-gauthier** [comment] 2023-10-23 15:39
I am still unable to reproduce the issue you are describing.  I'm going to close this issue for now, but feel free to re-open or file a new issue if you can provide screenshots, more detail on how to repro, etc.

**Closed by paul-gauthier** 2023-10-23 15:39 UTC
Labels: question

**Comment by ColtonKinstley** [comment] 2025-03-26 10:37
I'm having the same problem.

**Comment by Sattva-108** [comment] 2025-06-06 20:25
Not sure what causing this, but yeah my cmd.exe and Intellij Terminal today in aider get stuck 

```Tokens: 14k sent, 933 received.
Applied edit to pfQuest-master\debug.lua
Commit 78555f1 chore: обновить комментарий для команды глубокой проверки

/pfqdeep <ID_квеста>
Run shell command? (Y)es/(N)o/(D)on't ask again [Yes]: d
You can use /undo to undo and discard each aider commit.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────pfQuest-master\debug.lua
> v 
```

so my cursor just stack at character "v" in the end 
cannot input any text or delete text.
