### ISSUE TITLE
deepseek/coder suggests only how to edit the files but doesnt edit it directly. how to make it edit the files and make changes directly on the files?

### ISSUE THREAD

**Issue by sprappcom** [paul-gauthier/aider#998] opened 2024-08-04 01:10 UTC
### Issue

as titled

### Version and model info

latest
deepseek/deepseek-coder

**Comment by paul-gauthier** [comment] 2024-08-05 14:20
When reporting problems, it is very helpful if you can provide:

- Aider version
- LLM model you are using
- Any stack traces or error messages
- A description of what you were doing when the error happened. 

Including the “announcement” lines that aider prints at startup is an easy way to share some of this helpful info.

```
Aider v0.37.1-dev
Models: gpt-4o with diff edit format, weak model gpt-3.5-turbo
Git repo: .git with 243 files
Repo-map: using 1024 tokens
```

**Comment by 99cv** [comment] 2024-08-06 07:10
I can confirm.

Running `aider --model deepseek/deepseek-coder`

with
`Aider v0.47.1
Model: deepseek/deepseek-coder with diff edit format
Git repo: .git with 463 files
Repo-map: using 1024 tokens
`
and having two files added to context:
`99c_target/imports/ui/App.vue 99c_target/imports/ui/Login.vue`

and giving the following prompt:

> change the code to make `99c_target/imports/ui/Login.vue` the entry point of the app                                                                                                       

makes aider only giving suggestions instead of changing the code:
`
To make 99c_target/imports/ui/Login.vue the entry point of your Vue.js application, we need to configure the router to use this component as the default route. Since you've added           
99c_target/imports/ui/App.vue to the chat, we can proceed with the necessary changes.                                                                                                        

Let's assume you have a router configuration file (router.js or index.js) that we need to update. If you don't have one, please let me know, and I'll guide you through creating it.         

                                                                       Example router.js or index.js (if you have one)                                                                       

                                                                                                                                                                                             
 // router/index.js or router.js                                                                                                                                                             
 import { createRouter, createWebHistory } from 'vue-router';                                                                                                                                
 import Login from '99c_target/imports/ui/Login.vue';                                                                                                                                        
                                                                                                                                                                                             
 const routes = [                                                                                                                                                                            
   {                                                                                                                                                                                         
     path: '/',                                                                                                                                                                              
     name: 'Login',                                                                                                                                                                          
     component: Login                                                                                                                                                                        
   }                                                                                                                                                                                         
   // Add other routes here if needed                                                                                                                                                        
 ];                                                                                                                                                                                          
                                                                                                                                                                                             
 const router = createRouter({                                                                                                                                                               
   history: createWebHistory(),                                                                                                                                                              
   routes                                                                                                                                                                                    
 });                                                                                                                                                                                         
                                                                                                                                                                                             
 export default router;                                                                                                                                                                      
                                                                                                                                                                                             

                                                                                  Update main.js or main.ts                                                                                  

Ensure your main entry file (main.js or main.ts) imports and uses the router configuration:                                                                                                  

                                                                                                                                                                                             
 // main.js or main.ts                                                                                                                                                                       
 import { createApp } from 'vue';                                                                                                                                                            
 import App from './App.vue';                                                                                                                                                                
 import router from './router'; // Adjust the path according to your project structure                                                                                                       
                                                                                                                                                                                             
 createApp(App)                                                                                                                                                                              
   .use(router)                                                                                                                                                                              
   .mount('#app');                                                                                                                                                                           
                                                                                                                                                                                             
 createApp(App)                                                                                                                                                                              
   .use(router)                                                                                                                                                                              
   .mount('#app');                                                                                                                                                                           
                                                                                                                                                                                             

                                                                               Ensure App.vue uses the router
`

Even telling aider explicitly to change into `/chat-mode code` or use `change code directly` in the prompt did not change the behaviour.

**Comment by sprappcom** [comment] 2024-08-06 07:17
@99cv @paul-gauthier thx

**Comment by leanit-piotr** [comment] 2024-08-06 10:45
I have the same issue. it does not build files at all with Aider. It just tells you what to do. I hope it gets fixed quite soon. 🤞

**Comment by leanit-piotr** [comment] 2024-08-06 11:18
It seems I have found a work-around. At least it worked now once with another terminal. Please check guys if this isn't the problem with the built in VS Code terminal. In the standard command line all works as expected it seems...

**Comment by 99cv** [comment] 2024-08-06 11:55
@leanit-piotr 
I never use aider in the vs code terminal. So the issue occured in normal terminal in zsh shell as well.
My last task was to change just one line (finally just for testing purposes) in one file and aider with model deepseek/deepseek-coder was still just dropping suggestions instead of "doing the work".

@paul-gauthier 
with option `--edit-format whole` aider is doing changes again! Thanks!

**Comment by paul-gauthier** [comment] 2024-08-07 16:03
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Closed by paul-gauthier** 2024-08-07 16:03 UTC
Labels: question
