### ISSUE TITLE
aider opens files based on cwd, but completes based on git root dir.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [paul-gauthier/aider#95] opened 2023-07-13 22:39 UTC
Steps to reproduce:

1. start aider from a subdirectory in the git repo
2. /add <enter file completion>

What will happen:
Aider will suggest filenames based on what `git ls-files` in the root of the git repo will print.  When adding these files, aider will say they do not exist:

<img width="677" alt="image" src="https://github.com/paul-gauthier/aider/assets/339369/00b007ec-e761-4dd9-951b-68558712ad8c">

What should happen:
Either completion should be adjusted to current directory, or aider should read the file by adjusting cwd to the git root.

**Comment by alexanderkjeldaas** [comment] 2023-07-13 22:44
Aider chat history etc. is in the git root dir, so maybe the logical approach is that the completion and everything stays as-is, just that aider changes directory to the root before reading files.

**Comment by paul-gauthier** [comment] 2023-07-23 13:16
Thanks for reporting this! It was also reported recently in issue #139.

As you noted, the root cause was inconsistent handling of paths when aider is launched from a directory which is not the the git working directory (root). I made things consistent.

Now, when you are using in-chat commands insider aider you are always working with paths that are relative to the git working directory, even if you launch aider from elsewhere in your filesystem (inside or outside of the git repo). I think this the simplest and clearest way to handle things. 

It's worth noting that it handles the case where you run `aider /path/to/a/git/repo` from a place completely outside that repo.  I think this situation argues pretty strongly for the "use paths relative to the repo" approach.

**Comment by paul-gauthier** [comment] 2023-07-24 17:25
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Closed by paul-gauthier** 2023-07-24 17:25 UTC
Labels: bug
