### ISSUE TITLE
Improve accuracy of aider's 'self assembly' git stats by using 'git blame ignore' for formatting by black

### ISSUE THREAD

**Issue by 0xdevalias** [paul-gauthier/aider#627] opened 2024-05-30 06:19 UTC
### Issue

RE: https://aider.chat/2024/05/24/self-assembly.html

> This number is probably a significant undercount, because periodic reformatting by `black` is likely obscuring aider’s authorship of many lines.

If you wanted to improve the accuracy of these stats, you could potentially use `git`'s `--ignore-rev`, `--ignore-revs-file`, `.git-blame-ignore-revs`:

- https://www.stefanjudis.com/today-i-learned/how-to-exclude-commits-from-git-blame/
  - https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revltrevgt
  - https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revs-fileltfilegt
  - https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view
- https://stackoverflow.com/questions/34957237/can-i-configure-git-blame-to-always-ignore-certain-commits-want-to-fix-git-blam

### Version and model info

N/A

**Comment by paul-gauthier** [comment] 2024-06-04 17:09
I don't think this solves the issue. The problem is that my human edits invoke black on the files I touch, which may then fiddle with lines that aider wrote but which were never reformatted previously. There aren't purely "black reformat commits" that need to be elided from the blame chain. It's a side effect of my edits.

**Comment by 0xdevalias** [comment] 2024-06-07 07:36
> There aren't purely "black reformat commits" that need to be elided from the blame chain. It's a side effect of my edits.

@paul-gauthier Ah, true. Yeah, that would definitely make it harder then.

While it's probably too hard to apply retroactively, what I try and do in my codebases is make a separate 'formatting' commit if I notice unrelated things changed. That way if/when it comes to reviewing, I know that I can basically just ignore/skip past the formatting commits.

**Comment by paul-gauthier** [comment] 2024-06-10 22:29
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Closed by paul-gauthier** 2024-06-10 22:29 UTC
Labels: question
