### ISSUE TITLE
(Feature request) Documentation implementation

### ISSUE THREAD

**Issue by AndyMik90** [paul-gauthier/aider#280] opened 2023-10-12 19:03 UTC
Aider could go to the next level by incorporating a way for us to insert what documentation we would like chatgpt4 to take into context to get away from the knowledge cut-off.

**Comment by paul-gauthier** [comment] 2023-10-12 20:16
Thanks for trying aider!

This seems to be a duplicate of #69, so closing it for now.

**Closed by paul-gauthier** 2023-10-12 20:16 UTC
