### ISSUE TITLE
Let aider grok and configure the environment and run commands autonomously

### ISSUE THREAD

**Issue by Emasoft** [paul-gauthier/aider#648] opened 2024-06-06 03:32 UTC
### Issue

Aider is great. But it could be much better. For example, letting it to install tjings, run things, configure the environment and the projects directly. Currently it requires our intervention for 90% of those actions. Aider always asks the user to run this, run that. But isn’t it just a bunch of commands? It should be able to run them autonomously.  Just ask confirmation before running them.
What about letting Aider to examine the environment, the configuration files in every directory and subdirectory (.env, .bashrc, .zshrc, .jslint, requirements.txt, .toml, .gitignore, .cfg, .ini, etc.) and letting it to handle the configurations, the dependencies and the installed tools?. Once it understands the current configuration, it can also separate the projects and the sub projects in a folder, so that (for example) it won't mix pyprojects.toml files anymore when it edits them. (Many times I’ve found the .toml configurations of a project from a sub folder being copied to another subfolder ‘pyproject.toml’). 
Once aider groks the environment, it can also be able to understand if it is running in a docker, in a sandbox, in a devbox or in a github/microsoft workspace, etc. So it would finally stop trying to fix with the wrong configuration files in project/workspace/ instead of those in ~/. He must be able to access and understand dot files from the true root parent folder outside the project/workspace folder, so that he can correctly change the various configurations and permissions. Atbthe moment it doesn’t seem to understand what the right configurations file are or where it can find them. Aider needs more than a map of the git repo.. it needs a map of the entire dev environment.
Configurations files ARE part of the code after all, and when in dev mode they must be taken in consideration by Aider every time he makes changes to the source of the project. 
For example: "change my linter for JavaScript from eslint to jshint" or "extend the Python max line length to 120 characters in the riff configuration" or "migrate from Antigen to Antidote" or "install yarn-audit-fix and add it to my git hooks" or "add @parcel/diagnostic to the tests to run on this project" or "automatically add and commit to git all source files that pass the pytests," or "separate those two folders in two different pip projects", or "create the necessary boilerplate to make this script a complete pip package with tests/hooks/CI/github-scripts/logs/docs, etc. and publish it on github and pypi."
Maybe this would require to write some functions calling scripts to make easier for Aider to interact with the environment, but the alternative, since you cannot stop aider from trying to change things outside of the code, is to let it make a mess. My proposed solution is to make aider grok the environment he works in along with the projects configurations to enable it to making changes in a safe way with the help of some solid function calling scripts. As projects grow bigger and get more complex, aider ends up becoming a danger since it modifies so many things at the same time that it is easy to let some major errors or misconfigurations slip in undetected until it is too late.

**Comment by Michal-Mikolas** [comment] 2024-06-07 09:36
👍 I just wanted to submit an issue about "Let Aider run commands". It would be huge help improvement.

**Comment by paul-gauthier** [comment] 2024-06-10 22:31
This looks like a duplicate of #528, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-06-10 22:31 UTC
