### ISSUE TITLE
Uncaught AttributeError in sendchat.py line 30

### ISSUE THREAD

**Issue by asonawalla** [paul-gauthier/aider#1626] opened 2024-09-22 01:02 UTC
Aider version: 0.54.12
Python version: 3.12.6
Platform: macOS-15.0-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 24.0.0 (64bit)
Git version: git version 2.39.5 (Apple Git-154)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 682, in main
    if args.message:
            ^^^^^^^^^
  File "base_coder.py", line 730, in run
    def get_input(self):
                    ^^^^^
  File "base_coder.py", line 773, in run_one
    return
  File "base_coder.py", line 1183, in send_message
    content += "\n^C KeyboardInterrupt"
                    ^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1862, in auto_commit
    context += "\n" + msg["role"].upper() + ": " + msg["content"] + "\n"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 106, in commit
    elif self.attribute_commit_message_committer:
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 186, in get_commit_message
    continue
             
  File "sendchat.py", line 38, in wrapper
    retry_exceptions(),
    ^^^^^^^^^^^^^^^^^^
  File "sendchat.py", line 30, in retry_exceptions
    litellm.llms.anthropic.chat.AnthropicError,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'litellm.llms.anthropic' has no attribute 'AnthropicError'

```

**Comment by asonawalla** [comment] 2024-09-22 01:03
I'd also like to add that the auto-bug reporter is really awesome ❤️

**Comment by asonawalla** [comment] 2024-09-22 01:05
It might also be germane that this was a command run in an empty repo (git init but no commits yet).

**Comment by paul-gauthier** [comment] 2024-09-22 01:29
This looks like a duplicate of #1278, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-09-22 01:29 UTC
