### ISSUE TITLE
Git Submodule support

### ISSUE THREAD

**Issue by CUexter** [paul-gauthier/aider#1311] opened 2024-09-03 08:43 UTC
### Issue

Currently, when i try to add files in a submodule, it simply just fails to look inside.

### Version and model info

Aider: v0.53.0
Model: openrouter/sonnet

**Comment by paul-gauthier** [comment] 2024-09-03 15:29
This looks like a duplicate of #339, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-09-03 15:29 UTC
