### ISSUE TITLE
Uncaught UnicodeDecodeError in utils.py line 241

### ISSUE THREAD

**Issue by asahpchoi** [paul-gauthier/aider#1527] opened 2024-09-14 02:54 UTC
Aider version: <module 'aider.__version__' from 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aider\\__version__.py'>
Python version: 3.10.0
Platform: Windows-10-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.45.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 7, in <module>
    sys.exit(main())
  File "main.py", line 698, in main
    coder.run()
  File "base_coder.py", line 735, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 772, in run_one
    message = self.preproc_user_input(user_message)
  File "base_coder.py", line 764, in preproc_user_input
    self.check_for_urls(inp)
  File "base_coder.py", line 799, in check_for_urls
    inp += self.commands.cmd_web(url)
  File "commands.py", line 148, in cmd_web
    res = install_playwright(self.io)
  File "scrape.py", line 61, in install_playwright
    success, output = utils.run_install(chromium_cmd)
  File "utils.py", line 241, in run_install
    char = process.stdout.read(1)
UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 1: illegal multibyte sequence

```

**Comment by paul-gauthier** [comment] 2024-09-20 18:52
This looks like a duplicate of #1514, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-09-20 18:52 UTC
