### ISSUE TITLE
Cant add folder via '/add' command

### ISSUE THREAD

**Issue by erik-balfe** [paul-gauthier/aider#1175] opened 2024-08-25 17:39 UTC
### Issue

I can not use /add command with folders. I can add files by any path but not folders. Below is an example.

Example of adding a file from build folder in current directory:
```
> /add build/settings.js                                                                                                                          

Added /var/home/mypath/build/settings.js to the chat
```

Right after that i try to add the whole build folder:
```
> /add build                                                                                                                                      

No files matched 'build'. Do you want to create /var/home/mypath/build? [Y/n]  
* here i pressed 'Y'
/var/home/mypath/build: is a directory
Unable to read /var/home/mypath/build
```
Tried with some other folder names in several directories. Tried to restart the program. So in any situation I get this issue

### Version and model info

AIder: v0.52.1
model: deepseek/deepseek-coder
dark-mode: true
restore-chat-history: true

**Comment by paul-gauthier** [comment] 2024-08-25 19:19
Thanks for trying aider and filing this issue.

I think the problem is that the "build" subdir is not part of your git repo (which makes sense). Aider isn't willing to recursively add a dir tree to the repo. I've added a proper error message now that explains what's going on, like this:

```
> /add a-dir-not-in-repo

Directory /Users/gauthier/Projects/aider-demo/a-dir-not-in-repo is not in git.
You can add to git with: /git add /Users/gauthier/Projects/aider-demo/a-dir-not-in-repo
```

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment] 2024-08-26 21:17
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Closed by paul-gauthier** 2024-08-26 21:17 UTC
Labels: bug, fixed
