### ISSUE TITLE
New version with new preview gpt4 forgets what it is doing A LOT!

### ISSUE THREAD

**Issue by Dougie777** [paul-gauthier/aider#328] opened 2023-11-08 01:50 UTC
I have been using aider for 2 months now and its been amazing.  The most stable version was the one preceding this one I think.  Anyway today things went south.

I have been using aider all day today.  At first I was excited to see the fast generation with the new preview gpt4 model.  But all day I am getting the same behaviour.  It starts making modifications correctly, but seems to forget to finish.  For example if it is putting a loop around some existing code, it will start the loop fine, then later forget to close the loop with } (brackets).  Or in another case it is supporsed to add a dirty flag to a function and then return true or false based on this flag.  It correctly declares the flag, sets the flag as dirty properly, then forgets to add a return $flag at the end.  It is like it just forgets what it is doing !!  I have been cutting and pasting code into gpt4 manually today to get it to work (or just coding manually ...  oh no lol).  

Anyway aider is an amazing tool.  I hope we can get this sorted soon.  Thanks so so much for you hard work!

**Comment by paul-gauthier** [comment] 2023-11-14 21:39
Duplicate of #343.

**Closed by paul-gauthier** 2023-11-14 21:39 UTC
