### ISSUE TITLE
Support custom HTTP header via model settings and/or global config

### ISSUE THREAD

**Issue by bitnom** [paul-gauthier/aider#888] opened 2024-07-19 04:50 UTC
### Issue

Enhancement: User-configurable HTTP headers to be forwarded to API (optional)

LiteLLM accepts `extra_headers`:

https://github.com/BerriAI/litellm/blob/17575b1846346ee7c1e22117885f8889b7688a1a/docs/my-website/docs/providers/anthropic.md?plain=1#L188

```python
from litellm import completion
messages = [{"role": "user", "content": "What is Anthropic?"}]
response = completion(
    model="claude-3-5-sonnet-20240620", 
    messages=messages, 
    extra_headers={"anthropic-beta": "max-tokens-3-5-sonnet-2024-07-15"}
)
```

Additionally, a per-model `extra_headers` setting would be more useful and robust than a global one. Both could be supported.

Resolves https://github.com/paul-gauthier/aider/issues/867

### Version and model info

Aider v0.45.0

**Comment by paul-gauthier** [comment] 2024-07-22 07:14
This looks like a duplicate of #867 , so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-07-22 07:14 UTC
