### ISSUE TITLE
Changable base prompt

### ISSUE THREAD

**Issue by david-strejc** [paul-gauthier/aider#821] opened 2024-07-08 16:51 UTC
### Issue

Would it be good idea to make base prompt changable to Aider behave in different way? For example if we need aider to refactor code he is sometimes confused how to do that. My question and suggestion is - what about having multiple "base prompts" and those can be changed via /actlike ... for example /actlike refactoringAgent (something simmilar).

This will also make users be able to experiment with different prompts - they can be defined in users aider home config directory.

**Comment by paul-gauthier** [comment] 2024-07-12 09:08
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/faq.html#can-i-change-the-system-prompts-that-aider-uses

**Comment by fferreres** [comment] 2024-07-13 05:39
I found base_coder and the modified coders and their codes intractable. But the " help"  coder has been helpful for a minimalist understanding of it, based on io's def cmd_help(self, args) along with the coder and prompt for 'help'. Refactoring anything is futile right now, as is exploring anything that is not immediate code code code code code code code.

**Comment by paul-gauthier** [comment] 2024-07-22 07:01
This looks like a duplicate of #821, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-07-22 07:01 UTC
Labels: question
