### ISSUE TITLE
v0.8.1 bug: only works for keys with gpt-4 access

### ISSUE THREAD

**Issue by jaysidri** [paul-gauthier/aider#71] opened 2023-07-08 09:37 UTC
I've installed Aider using pip install aider-chat and installed ctags using homebrew (running Python 3.11.3 in conda env).

It's not responding to anything I give it -- I've attached a screen recording here: https://imgur.com/a/LgDRvbH

Did something break?

**Comment by dicolasi** [comment] 2023-07-08 10:53
got exactly the same problem

**Comment by dicolasi** [comment] 2023-07-08 11:07
The problem is with that version. Downgrading to version 0.8.0 works.

**Comment by paul-gauthier** [comment] 2023-07-08 13:14
Apologies! I just released v0.8.2 which solves this issue. 

I jumped the gun and marked `gpt-4` as "generally available". Apparently it is not 100% rolled out yet. So this issue was a bug in v0.8.1 that affected anyone without `gpt-4` access.

You can also work around the bug with v0.8.1 installed by running `aider --model gpt-3.5-turbo-16k`

**Comment by dicolasi** [comment] 2023-07-08 13:27
thanks @paul-gauthier . Can you please advise why I see this: 
```
API key does not support gpt-4, falling back to gpt-3.5-turbo-16k
Model: gpt-3.5-turbo-16k
```

I got a paid subscription with openai, and I generated an api key from my account. Am I missing something?

**Comment by paul-gauthier** [comment] 2023-07-08 13:40
@dicolasi glad to see the new version is working for you.

OpenAI has had a waiting list for gpt-4, so even a paid API account doesn't automatically get you access. So aider checks to see if your api key supports gpt-4, and if not it falls back to gpt-3.5-turbo-16k.

OpenAI just announced that soon they will open up gpt-4 to everyone with an API account:

https://openai.com/blog/gpt-4-api-general-availability

> We plan to open up access to new developers by the end of this month, and then start raising rate-limits after that depending on compute availability.

**Comment by dicolasi** [comment] 2023-07-08 13:44
amazing! This tool is great. Just testing it now. Quick question: is there a theme that change the colours for black terminal background? Blue on black is very hard to read :)

**Comment by paul-gauthier** [comment] 2023-07-08 14:01
Ya, there are command line / configs for all the colors. By default aider starts with colors that work well on a light background. If you find a pleasing set of colors for dark backgrounds, let me know. I have been meaning to add a `--dark-mode` switch with sensible dark colors.

```
  --user-input-color USER_INPUT_COLOR
                        Set the color for user input (default: green) [env var: AIDER_USER_INPUT_COLOR]
  --tool-output-color TOOL_OUTPUT_COLOR
                        Set the color for tool output (default: None) [env var: AIDER_TOOL_OUTPUT_COLOR]
  --tool-error-color TOOL_ERROR_COLOR
                        Set the color for tool error messages (default: red) [env var: AIDER_TOOL_ERROR_COLOR]
  --assistant-output-color ASSISTANT_OUTPUT_COLOR
                        Set the color for assistant output (default: blue) [env var: AIDER_ASSISTANT_OUTPUT_COLOR]
  --code-theme CODE_THEME
                        Set the markdown code theme (default: default, other options include monokai, solarized-dark, solarized-light) [env var: AIDER_CODE_THEME]
```

**Comment by paul-gauthier** [comment] 2023-07-08 16:00
If you install the latest from github, aider now has a `--dark-mode` switch that sets the colors like the attached image.

<img width="830" alt="2023-07-08_08-59-12" src="https://github.com/paul-gauthier/aider/assets/69695708/9edded89-19bd-41ee-94ae-b21b5a1cef28">

**Comment by paul-gauthier** [comment] 2023-07-08 16:02
I'm going to close this issue for now, but please feel free to re-open if you have further problems.

**Comment by dicolasi** [comment] 2023-07-08 16:03
That looks much better :)   
  

  

  

  
  
  
  
  
>

**Closed by paul-gauthier** 2023-07-08 16:02 UTC
