### ISSUE TITLE
Uncaught TypeError in main.py line 172

### ISSUE THREAD

**Issue by univers3** [paul-gauthier/aider#1861] opened 2024-10-01 12:33 UTC
Aider version: <module 'aider.__version__' from '/Users/damiano/Library/Python/3.10/lib/python/site-packages/aider/__version__.py'>
Python version: 3.10.10
Platform: macOS-14.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.1.0 (64bit)
Git version: git version 2.42.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 4, in <module>
    main()
  File "main.py", line 441, in main
    launch_gui(argv)
  File "main.py", line 172, in launch_gui
    if "-dev" in __version__:
TypeError: argument of type 'module' is not iterable

```

**Comment by paul-gauthier** [comment] 2024-10-01 17:50
Thanks for trying aider and filing this issue.

This looks like a duplicate of #1502. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-10-01 17:50 UTC
Labels: question
