### ISSUE TITLE
Uncaught TypeError in core.pyx line 14

### ISSUE THREAD

**Issue by JuvenileLocksmith** [paul-gauthier/aider#1765] opened 2024-09-26 20:24 UTC
Aider version: 0.57.1
Python version: 3.10.0
Platform: macOS-10.16-x86_64-i386-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 21.6.0 (64bit)
Git version: git version 2.24.3 (Apple Git-128)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 686, in main
    coder.run(with_message=args.message)
  File "base_coder.py", line 717, in run
    self.run_one(with_message, preproc)
  File "base_coder.py", line 766, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1204, in send_message
    lint_errors = self.lint_edited(edited)
  File "base_coder.py", line 1298, in lint_edited
    errors = self.linter.lint(self.abs_root_path(fname))
  File "linter.py", line 100, in lint
    lintres = cmd(fname, rel_fname, code)
  File "linter.py", line 117, in py_lint
    basic_res = basic_lint(rel_fname, code)
  File "linter.py", line 213, in basic_lint
    parser = get_parser(lang)
  File "core.pyx", line 19, in tree_sitter_languages.core.get_parser
  File "core.pyx", line 14, in tree_sitter_languages.core.get_language
TypeError: __init__() takes exactly 1 argument (2 given)

```

**Comment by fry69** [comment] 2024-09-26 20:46
Thank you for filing this issue.

Can you please try to install or reinstall aider in a separate Python environment? Either with `venv` or `pipx`?

Please remove the existing environment/aider installation first, e.g. with `pipx`:
```shell
$ pipx uninstall aider-chat
uninstalled aider-chat! ✨ 🌟 ✨
```
```shell
$ pipx install aider-chat
  installed package aider-chat 0.57.1, installed using Python 3.12.6
  These apps are now globally available
    - aider
done! ✨ 🌟 ✨
```

This document may be helpful -> https://aider.chat/docs/troubleshooting/imports.html

**Comment by paul-gauthier** [comment] 2024-09-27 21:29
Thanks for trying aider and filing this issue.

This looks like a duplicate of #1236. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-09-27 21:29 UTC
Labels: question

**Comment by JuvenileLocksmith** [comment] 2024-10-08 23:15
Supremely useful approach, now I can use it anywhere! Many thanks.
