### ISSUE TITLE
Uncaught TypeError in symbolic.py line 413

### ISSUE THREAD

**Issue by ianchov** [paul-gauthier/aider#1525] opened 2024-09-13 19:55 UTC
Aider version: 0.56.0
Python version: 3.12.2
Platform: macOS-14.6.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.39.3 (Apple Git-146)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 698, in main
    coder.run()
  File "base_coder.py", line 735, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 772, in run_one
    message = self.preproc_user_input(user_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 761, in preproc_user_input
    return self.commands.run(inp)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 221, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 196, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "commands.py", line 432, in cmd_undo
    self.raw_cmd_undo(args)
  File "commands.py", line 483, in raw_cmd_undo
    current_branch = self.coder.repo.repo.active_branch.name
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base.py", line 1036, in active_branch
    return self.head.reference
           ^^^^^^^^^^^^^^^^^^^
  File "symbolic.py", line 413, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to '117456a2f3fc5b07f68ca2492893a6c28baa4d89'

```

The workflow is: 
* aider worked out some stuff
* exited aider
* git checkout a commit to rollback stuff
* worked some stuff
* started aider again and asked it to do something

**Comment by fry69** [comment] 2024-09-13 20:03
Thank you for filing this issue.

> git checkout a commit to rollback stuff

Looks like GitPython (which aider uses), really does not like the detached head state you put your repository in. For now I'd recommend to avoid this and start aider only when you are on a branch.

**Comment by paul-gauthier** [comment] 2024-09-20 18:42
This looks like a duplicate of #1506, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-09-20 18:42 UTC
