### ISSUE TITLE
Uncaught TypeError in main.py line 172

### ISSUE THREAD

**Issue by Da3n0n** [paul-gauthier/aider#1520] opened 2024-09-13 15:01 UTC
Aider version: <module 'aider.__version__' from 'C:\\Users\\Dannan\\AppData\\Roaming\\Python\\Python312\\site-packages\\aider\\__version__.py'>
Python version: 3.12.5
Platform: Windows-11-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 11 (64bit)
Git version: git version 2.46.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "main.py", line 781, in <module>
    status = main()
             ^^^^^^
  File "main.py", line 422, in main
    launch_gui(argv)
  File "main.py", line 172, in launch_gui
    if "-dev" in __version__:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'module' is not iterable

```

**Comment by fry69** [comment] 2024-09-13 16:26
Thank you for filing this issue.

There seems to be a bug launching the GUI/browser currently in this setup, the terminal version of aider should work fine though.

**Comment by paul-gauthier** [comment] 2024-09-20 18:57
This looks like a duplicate of #1502, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-09-20 18:57 UTC
