### ISSUE TITLE
After trying out Cursor edit

### ISSUE THREAD

**Issue by goukisun** [paul-gauthier/aider#1465] opened 2024-09-10 08:38 UTC
### Issue

I find 2 useful features
1. codebase indexer， can embedding whole code。but it use remote server to storage vectorDB
2. search web when chat
i think aider can add these features， and use local vector DB

### Version and model info

master version

**Comment by paul-gauthier** [comment] 2024-09-11 15:22
Thanks for trying aider and filing this issue.

This looks like a duplicate of #1005 and #530, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-09-11 15:22 UTC
