### ISSUE TITLE
Tokens leak?

### ISSUE THREAD

**Issue by ErykCh** [paul-gauthier/aider#863] opened 2024-07-14 22:33 UTC
### Issue

While checking the token consumption of the application I am writing (because it uses the LLM model), I noticed something strange. Over 11,000 tokens for a small change assigned to Aider. So I called /tokens and it showed 1792 tokens. As a test, I told Aider to make a simple change. And Aider sent 11301 tokens?

![image](https://github.com/user-attachments/assets/019f716c-1c2f-46f8-be23-9d6c24a9ec7b)

### Version and model info

Aider v0.43.5-dev
Models: openrouter/anthropic/claude-3.5-sonnet with diff edit format, weak model openrouter/anthropic/claude-3-haiku
Git repo: .git with 46 files
Repo-map: using 2028 tokens
Added .aider.memory.md to the chat.

**Comment by paul-gauthier** [comment] 2024-07-17 13:50
Thanks for trying aider and filing this issue. It looks like you have identified a bug. The `/tokens` command is not showing the tokens used by the repo-map. I'll get this fixed.

**Comment by paul-gauthier** [comment] 2024-07-18 15:53
The `--map-tokens` is a guideline, not a hard limit.

Sorry, I am unable to reproduce this. Are you able to make this happen again? If so, can you share the announce lines that aider prints on launch as well as the `/tokens` output from that same session?

Are you sure that the screenshot you shared of `/tokens` is from the same session as usage lines you highlighted in the openrouter screenshot?

Because the openrouter usage lines look like they were from a session where you used aider *without adding any files to the chat* and while operating inside a git repo. And the `/tokens` screenshot looks like you have added a file and are running aider without an active repomap because maybe you are not inside a git repo.

**Comment by ErykCh** [comment] 2024-07-19 05:45
> Are you sure that the screenshot you shared of /tokens is from the same session as usage lines you highlighted in the openrouter screenshot?

yes

> Because the openrouter usage lines look like they were from a session where you used aider without adding any files to the chat and while operating inside a git repo.

It seems that I have still this session open.

so let's delve into it

aider start and first task
after I saw how many tokens it used, I called /tokens

![image](https://github.com/user-attachments/assets/b411d3f0-3454-4d8f-9e1b-ff7d60e2bb4e)

so I repeated with another small change
![image](https://github.com/user-attachments/assets/45e73fd3-a1e3-4b04-aabf-22acf836ced6)

/ls from this session
![image](https://github.com/user-attachments/assets/948c42ff-ff88-48a9-95dd-cc329417390a)


I did another test now. In the same session.
on the beginning /tokens and you see repo-map
than remove a file
adding the same file from this ticket
small change
there is no repo
and high token usage despite small file
![image](https://github.com/user-attachments/assets/b74b9cbc-c25a-4057-b09b-bed6036a7f52)

![image](https://github.com/user-attachments/assets/0455bc64-e042-4e37-ad46-0e53ffadd213)



when I drop this file, it is on the list printed by /ls

**Comment by ErykCh** [comment] 2024-07-19 06:05
I closed the session, updated to the latest version of Aider.

Aider v0.45.1
Models: openrouter/anthropic/claude-3.5-sonnet with diff edit format, weak model openrouter/openai/gpt-4o-mini
Git repo: .git with 46 files
Repo-map: using 2028 tokens
Added .aider.memory.md to the chat.


There is still no repo-map for this file.

![image](https://github.com/user-attachments/assets/19eef387-63e1-45dd-ac71-84b4e8e6b42a)

**Comment by mr-september** [comment] 2024-07-26 07:13
I've also ran into a similar issue. I can clear chat history and start a new session, and the first prompt immediately says it's using a million tokens. From my `.aider.chat.history.md`:

```
#### Example_File.ipynb for how coding could be improved. For example, could the plotting function be summarized and called instead of writing the full code each time?  

To improve the coding in `Example_File.ipynb`, we can focus on refactoring the plotting function to avoid repeating the full code each time. The most likely file that needs to be edited is:

- `Research\Example_File.ipynb`

Please add `Research\Example_File.ipynb` to the chat so I can propose specific changes.

>  
>  
> Model deepseek/deepseek-coder has hit a token limit!  
> Token counts below are approximate.  
>  
> Input tokens: ~1,204,876 of 128,000 -- possibly exhausted context window!  
> Output tokens: ~0 of 4,096  
> Total tokens: ~1,204,876 of 128,000 -- possibly exhausted context window!  
```

I also notice that neither `.aider.chat.history.md` nor `.aider.input.history` are actually empty files after I cleared chat history in the browser button. `.aider.chat.history.md` is quite big, 76 Kb. Could this be relevant to the issue? Is it trying to send the entire `.aider.chat.history.md` in the prompt?

**Comment by paul-gauthier** [comment] 2024-07-30 18:31
@mr-september you should run `/tokens` to see what's using that 1M tokens. Did you add those `.aider...` files to your repo and to the chat?

**Comment by paul-gauthier** [comment] 2024-07-30 18:34
@ErykCh any chance you can share that specific file with me? Wondering if it is somehow causing the repo map to crash in the tokens display.

**Comment by mr-september** [comment] 2024-07-31 09:44
@paul-gauthier How/where do I run `/tokens`? I am currently running with `python -m aider.main --model deepseek/deepseek-coder --browser` , through Windows/VS Code. The terminal in VS code is not available for manual inputs, while running `/tokens` in the chat just seems to ask the LLM a question.

I think those `.aider...` files were prompted after installing `aider-chat`, maybe on the first time I tried to run it.

**Comment by paul-gauthier** [comment] 2024-08-02 09:59
This is expected when you are running with no added files. Aider uses a larger repo map, so that the LLM can thoroughly understand your code base. Since you haven't added any files, the LLM is encouraged to suggest which files need to be edited based on your chat requests. To make good suggestions, it helps to have a larger repo map.

**Comment by paul-gauthier** [comment] 2024-08-06 13:09
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Closed by paul-gauthier** 2024-08-06 13:09 UTC
Labels: bug
