### ISSUE TITLE
Uncaught TypeError in core.pyx line 14

### ISSUE THREAD

**Issue by johnconnor-sec** [paul-gauthier/aider#1548] opened 2024-09-15 18:01 UTC
Aider version: 0.56.0
Python version: 3.12.4
Platform: Linux-6.8.0-41-generic-x86_64-with-glibc2.39
Python implementation: CPython
Virtual environment: No
OS: Linux 6.8.0-41-generic (64bit)
Git version: git version 2.43.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 698, in main
    coder.run()
  File "base_coder.py", line 735, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 778, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1213, in send_message
    lint_errors = self.lint_edited(edited)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1307, in lint_edited
    errors = self.linter.lint(self.abs_root_path(fname))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "linter.py", line 100, in lint
    lintres = cmd(fname, rel_fname, code)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "linter.py", line 117, in py_lint
    basic_res = basic_lint(rel_fname, code)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "linter.py", line 213, in basic_lint
    parser = get_parser(lang)
             ^^^^^^^^^^^^^^^^
  File "core.pyx", line 19, in tree_sitter_languages.core.get_parser
  File "core.pyx", line 14, in tree_sitter_languages.core.get_language
TypeError: __init__() takes exactly 1 argument (2 given)

```

**Comment by fry69** [comment] 2024-09-15 18:08
Thank you for filing this issue.

This looks similar to #1484, it may be related to broken dependencies. This document may be helpful

https://aider.chat/docs/troubleshooting/imports.html

If possible and available try using `pipx` to install aider, it is much less painful than either
- `pip` (which interferes with the main Python installation)
- system packages (which often do not get the dependencies correct, sadly)

`pipx` creates a `venv` automatically for you and handles everything behind the scenes, I strongly recommend to use this method for installing aider.

**Comment by paul-gauthier** [comment] 2024-09-20 18:38
This looks like a duplicate of #1236, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-09-20 18:38 UTC
