### ISSUE TITLE
GPT-4 Turbo generating "invalid edit blocks"

### ISSUE THREAD

**Issue by forrestcoward** [paul-gauthier/aider#343] opened 2023-11-11 18:29 UTC
Hey there,

I was trying out Aider this morning to add a feature onto a small code base but hit many `malformed response, aborting` trying to get aider working.

Steps to reproduce (aider v0.17.0):
1. Clone https://github.com/forrestcoward/MTG-Card-Generator.
2. At root of repository, run `aider --model gpt-4-1106-preview`.
3. Add all `cs` and `tsx` files with `/add`.
4. Aider prompt: `I want to add a button on the webpage that allows users to download an image of the generated card. This image should include the entire card (image, card text, and explanation, if it was generated). The download button should have an appropriate
icon and should show up in a drop down underneath each card.`

![image](https://github.com/paul-gauthier/aider/assets/1037002/0c487673-2bf1-4710-a0e8-7c8b4b259725)

![image](https://github.com/paul-gauthier/aider/assets/1037002/d512edb7-3104-40e5-9645-7f7265252d30)

I am sure you are aware of this problem with the ability to successfully generate and apply diffs and this is something that is a big challenge to get right, but I did not see any open issues about the malformed response.

**Comment by lucien2k** [comment] 2023-11-13 09:25
I've been having this a lot as well, I wonder if there's a way to prime chatgpt to prevent it giving bad responses. I think its partly down to it creating bad diffs

**Comment by w3bdesign** [comment] 2023-11-14 22:05
Have you tried the `gpt-4-0314` model?
I've heard it is better at coding than the newer models. 
Might also be better than `gpt-4-0613`

**Comment by paul-gauthier** [comment] 2023-11-14 23:54
@w3bdesign I've shared some fairly extensive benchmarking results comparing all of the openai models. Here's the latest one:

https://aider.chat/docs/benchmarks-1106.html

**Comment by paul-gauthier** [comment] 2023-11-15 13:36
I published some improved prompting which may help the issues we've been seeing with GPT-4 Turbo. The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by divergent-synapse** [comment] 2023-11-15 13:59
Appreciate the quick turnaround on this! I was having this issue too but hadn't said anything yet. I'll give it a whirl and sound off how it goes.

Out of all the AI coding tools I've tinkered with over the last several months, this one has been the one I keep coming back to. Amazing work.

**Comment by lucien2k** [comment] 2023-11-16 05:53
One thing I've just observed is that when there's multiple code blocks that change, it sometimes gets in a mess.

I had a case where it generated 3 blocks, first one applied, second one failed. It then gave gpt a telling off "DO NOT skip blank lines, comments, docstrings, etc!". It re-generated all three code blocks but the first block was already applied so it failed again.

**Comment by code-groove-alien** [comment] 2023-12-04 21:53
> I published some improved prompting which may help the issues we've been seeing with GPT-4 Turbo. The change is available in the main branch. You can get it by installing the latest version from github:
> 
> ```
> python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
> ```
> 
> If you have a chance to try it, let me know if it works better for you.

Hey Paul really nice work on this git , thanks a ton for your effort !  Just to update you I am still getting the Malformed errors and its exiting after 3 malformed responses. I guess I'll just use GPT-4-0613 model for now
![image](https://github.com/paul-gauthier/aider/assets/125309988/20cbd1b1-1e9a-45a7-9c2a-b11f7ebaf8e9)

**Comment by code-groove-alien** [comment] 2023-12-04 21:57
> One thing I've just observed is that when there's multiple code blocks that change, it sometimes gets in a mess.
> 
> I had a case where it generated 3 blocks, first one applied, second one failed. It then gave gpt a telling off "DO NOT skip blank lines, comments, docstrings, etc!". It re-generated all three code blocks but the first block was already applied so it failed again.
> 
> I've had reasonable luck with telling it to provide me with a single code block rather than multiple on a re-try.

Hey lucien , same this here "DO NOT skip blank lines, comments, docstrings, etc!" but GPT-4 TURBO cant figure anything out once this happens ran the same 5 times and it will keep giving malformed responses . would be good if we could see the malformed response where exactly its having a problem and then tweak the prompt

**Comment by lucien2k** [comment] 2023-12-04 22:05
I wonder if that can be strengthened. I find that it often tries to do /* Existing code */ or similar.

I've been using "Please provide complete SEARCH/REPLACE blocks without skipping any code" to try to encourage it.

**Comment by akiselev** [comment] 2023-12-06 20:54
It's not just skipping blank lines and such. There's a fundamental problem in how `gpt-4-1106-preview` rewrites indentation in the SEARCH block as if it's auto-formatting the code to some style guide.

I think I've found a (relatively) reproducible example in the [flameshot repo](https://github.com/flameshot-org/flameshot/blob/master/src/core/flameshot.cpp#L318).

If you run (some variation of the prompt):

```
/add src/core/flameshot.cpp
add comments to explain the code inside `requestCapture`
```

It will frequently fail on the following code:

```cpp
void Flameshot::requestCapture(const CaptureRequest& request)
{
    if (!resolveAnyConfigErrors()) {
        return;
    }

    switch (request.captureMode()) {
        case CaptureRequest::FULLSCREEN_MODE:
            QTimer::singleShot(request.delay(),
                               [this, request] { full(request); });
            break;
        case CaptureRequest::SCREEN_MODE: {
            int&& number = request.data().toInt();
            QTimer::singleShot(request.delay(), [this, request, number]() {
                screen(request, number);
            });
            break;
        }
        case CaptureRequest::GRAPHICAL_MODE: {
            QTimer::singleShot(
              request.delay(), this, [this, request]() { gui(request); });
            break;
        }
        default:
            emit captureFailed();
            break;
    }
}
```

because it will remove one level of indentation from the switch cases. `gpt-4-0314` also sometimes creates a bad SEARCH block but it usually manages to create a good edit by the third one. `gpt-4-1106-preview` screws it up significantly more frequently

**Comment by lucien2k** [comment] 2023-12-06 21:15
I guess the level of issue is language dependent. I’m mostly rust, the main issue I have is the skipping code and occasional missing close brace.

**Comment by paul-gauthier** [comment] 2023-12-17 21:42
Aider is using a new approach to stop GPT-4 Turbo from being lazy. I just merged a big change to the main branch that introduces a "unified diff" edit format. In benchmarks it massively reduces lazy coding by GPT-4 Turbo.

If you have a chance, please try it and let me know how it works for you.

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

There's also a new `--4-turbo` switch, which will launch aider with the `gpt-4-1106-preview` model.

Regardless of how you select GPT-4 Turbo, aider will use the new unified diff edit format by default. To switch back to the old SEARCH/REPLACE format, you can use `--edit-format diff`.

**Comment by paul-gauthier** [comment] 2024-01-02 18:44
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Closed by paul-gauthier** 2024-01-02 18:44 UTC
