### ISSUE TITLE
Terminal output in VSCode is broken

### ISSUE THREAD

**Issue by rappster** [paul-gauthier/aider#124] opened 2023-07-18 18:33 UTC
Hi there,

and first of: thanks a LOT for creating this awesome AI helper! It's really like having your senior developer live right in your Git repo - truly amazing!

I did notice, though, that the output in the VSCode terminal is "broken" in the sense that it repeatedly lists the  same chunks of prose and code over and over again. I think it happens each time there's code involved:

![image](https://github.com/paul-gauthier/aider/assets/1205659/63399a96-188a-4140-be5e-eb31d6059703)

**Comment by paul-gauthier** [comment] 2023-07-18 18:43
Thanks for trying aider and reporting this issue.

You might want to try running with `--no-pretty`. The install instructions mention this helps in VSCode:
https://aider.chat/docs/install.html#add-aider-to-your-editor-optional

**Comment by paul-gauthier** [comment] 2023-07-19 12:11
[I asked aider to disable pretty if it detects that it is running inside a VSCode terminal](https://github.com/paul-gauthier/aider/commit/7930cea227616b4dda40dbae7328b9561a4cbe19). 

I've merged a fix into the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment] 2023-07-20 14:22
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Closed by paul-gauthier** 2023-07-20 14:22 UTC
Labels: bug

**Comment by fahmad91** [comment] 2023-12-18 21:50
@paul-gauthier Any plans for a permanenet fix for this?

**Comment by paul-gauthier** [comment] 2023-12-18 22:04
As far as I can tell the problem is that vscode doesn't provide a fully capable terminal. 

Aider should be turning off fancy output when run inside vscode. Is that not working for you?

**Comment by fahmad91** [comment] 2023-12-18 22:10
> turning off fancy output when r

hmmm... so it's a limitation in the vscode terminal vs aider. I was thinking it might be related to the rich library, so I was hoping it would be fixed soon. 

aider does turn off the fancy output, which works as a workaround; however, it makes the output hard to read, so I'm not a big fan of it.

**Comment by paul-gauthier** [comment] 2023-12-18 22:52
You can always run aider in a real terminal window beside your vscode window.
