### ISSUE TITLE
Aider asking me to add files that are already added

### ISSUE THREAD

**Issue by markenzie** [paul-gauthier/aider#315] opened 2023-11-02 08:23 UTC
aider 0.16.3

I was experimenting with creating a tower defense game. Aider keeps asking for files it already has access to.

```
To implement this feature, we need to modify the following files:

 1 Wallet.js: We need to add a method to check if the wallet has enough resources to purchase a tower and another method
   to deduct the cost of the tower from the wallet.
 2 EntitySpawner.js: We need to modify the spawnEntities method to check if the wallet has enough resources before
   spawning a new tower and to increase the cost of the tower after each purchase.
 3 main.js: We need to modify the collectScrap function to add the collected scrap to the wallet.

Please add these files to the chat so I can propose the necessary changes.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Entity.js EntitySpawner.js Wallet.js main.js new_file_path\ParticleSystem.js
> /ls

Files in chat:

  Entity.js
  EntitySpawner.js
  Wallet.js
  main.js
  new_file_path\ParticleSystem.js

Repo files not in the chat:

  main-ecs.js
```

**Comment by HelgeS** [comment] 2023-11-15 14:19
I observe the same behavior with aider 0.17.0 and I think it's a bug.
I'm not sure why this happens, because it has been working properly before with the same file.

Here is my output:
```
> aider --model=gpt-4-1106-preview python/common.py 
Aider v0.17.0
Model: gpt-4-1106-preview
Git repo: .git
Repo-map: using 1024 tokens
Added python/common.py to the chat.
Use /help to see in-chat commands, run with --help to see cmd line args
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
python/common.py                                                                                                                              
> How can I make parse_json in python/common.py more efficient?                                                                               

To make the parse_json function in python/common.py more efficient, we can consider the following optimizations:                              

 1 Minimize lookups in the loop: Instead of repeatedly checking if a cluster is in partition_indices, we can use a defaultdict or setdefault  
   method to handle new clusters more efficiently.                                                                                            
 2 Use list comprehensions: They are generally faster than for-loops for creating lists or dictionaries because of localized variable lookups 
   and less function call overhead.                                                                                                           
 3 Avoid redundant dictionary lookups: Store frequently accessed data in local variables to reduce the number of dictionary lookups.          
 4 Use set operations: When adding edges, we can use set operations to add all edges at once instead of one by one in a loop.                 

Let's apply these optimizations to the parse_json function. Please add the python/common.py file to the chat so I can provide the exact       
changes using the SEARCH/REPLACE block.                                                                                                       

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
python/common.py                                                                                                                              
> /ls                                                                                                                                         

Files in chat:

  python/common.py

```

**Comment by paul-gauthier** [comment] 2023-11-15 15:39
@markenzie which model were you using?

**Comment by paul-gauthier** [comment] 2023-11-15 20:16
I have confirmed this is a bug. Thanks for filing it. Will fix it ASAP.

**Comment by datablets** [comment] 2023-11-15 20:19
As a hint, I removed this text from all prompts: ` and ask them to *add the files to the chat*`

And this: `I am not sharing any *read-write* files yet.`

And the problem went away. I'm sure you'll have a more elegant solution though, because I imagine those instructions are meant to prevent something else I haven't encountered yet.

**Comment by paul-gauthier** [comment] 2023-11-15 21:08
Ya, it wasn't a prompting issue. It was a bug in the repo-map implementation. I just pushed a fix to github.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by datablets** [comment] 2023-11-15 21:22
It didn't work for me unfourtunately, it forgets the files is in scope on the secodn request.

**Comment by paul-gauthier** [comment] 2023-11-15 21:37
@datablets are you sure you're running the newest from main branch? Sounds like you were also hacking on the prompt strings so maybe have a local dev build going there?

**Comment by datablets** [comment] 2023-11-16 05:37
Yes, I was changing some things around but to test the solution I downloaded the zip from the repo and replaced the files in my poject.

**Comment by paul-gauthier** [comment] 2023-11-16 20:02
Can you share a transcript that shows the problem you are having?

The bug was clearly an issue where aider was including files that were added to the chat twice in the GPT prompt, once as read-only and once as read-write. That bug was fixed, and has test coverage now.

So I'm not sure exactly what issue you are seeing now.

**Comment by datablets** [comment] 2023-11-17 22:06
Yeah sorry I must not have made a clean copy. I tried cloning into a fresh folder and I'm not seeing the issue. Cheers

**Comment by paul-gauthier** [comment] 2023-11-17 22:30
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Closed by paul-gauthier** 2023-11-17 22:30 UTC
Labels: bug, fixed
