### ISSUE TITLE
Error: summarizer unexpectedly failed for all models

### ISSUE THREAD

**Issue by lockmeister** [paul-gauthier/aider#1040] opened 2024-08-08 23:18 UTC
### Issue

I periodically get the error:
"summarizer unexpectedly failed for all models"

### Version and model info

aider 0.48.1
Sonnet 3.5

**Comment by paul-gauthier** [comment] 2024-08-09 18:14
Thanks for trying aider and filing this issue.

Anthropic's servers were crashing a lot yesterday. Is this still happening for you?

**Comment by paul-gauthier** [comment] 2024-08-19 17:49
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by paul-gauthier** [comment] 2024-09-05 15:16
This is typically caused by Anthropic's servers melting down. Please let me know if you see it happen consistently over time.

**Comment by TzviCons** [comment] 2024-09-24 20:23
I"m getting this too. And my configuration is set to use openai.

![image](https://github.com/user-attachments/assets/0fe27a8c-b48c-40da-8086-4db4125d189e)

![image](https://github.com/user-attachments/assets/002ceded-9efe-4eed-a7f4-2c9c0e5b2013)

```
Aider v0.56.0
Main model: gpt-4o-2024-08-06 with diff edit format
Weak model: gpt-4o-mini-2024-07-18
Git repo: .git with 1,829 files
Warning: For large repos, consider using --subtree-only and .aiderignore
See: https://aider.chat/docs/faq.html#can-i-use-aider-in-a-large-mono-repo
Repo-map: using 1024 tokens, auto refresh
Use /help <question> for help, run "aider --help" to see cmd line args
```

**Comment by paul-gauthier** [comment] 2024-09-24 20:29
@TzviCons  How did you install aider? What environment are you using? It looks like you don't have the correct set of dependencies installed. This doc may be helpful:

https://aider.chat/docs/troubleshooting/imports.html

**Comment by TzviCons** [comment] 2024-09-24 22:15
@paul-gauthier I've been using it for a while and it just started giving me this error. It did just run the self-update (see screenshot above). Is it possibly that the self-update didn't install all the needed dependencies?

**Comment by paul-gauthier** [comment] 2024-09-24 22:27
The latest version is 0.57.1 but your screenshot shows 0.56. 

Try aider --upgrade to move to the latest?

**Comment by TzviCons** [comment] 2024-09-29 12:56
It's been working fine for now. I suspect that the issue was caused by a failed self-update. The screenshot above prompts to run the update to 0.57.1 but when it starts aider, it shows the old version number 0.56

I'll close the issue for now.

**Closed** 2024-09-29 12:57 UTC
Labels: question
