### ISSUE TITLE
[Question]Can we make Aider execute shell/git command produced from user's prompt

### ISSUE THREAD

**Issue by mickitty0511** [paul-gauthier/aider#968] opened 2024-07-31 01:02 UTC
### [THIS IS A QUESTION]
When trying to ask aider to execute shell command with "Move me to a parent directory", it always only tells me about the cd command to be executed in the Windows terminal as well as git commands I want aider to execute.

I hope I would like aider to auto-execute shell/git command made when I ask aider to.

Does anyone have the best practices?
**\*Except the instructions where we execute those commands manually by ourselves. I'm sure I can do that.**

### Version and model info

aider 0.46.1
Model: gemini 1.5 pro

**Comment by lightningRalf** [comment] 2024-08-02 22:18
have a look over here: #528 
In the meantime you could just use the /run {insert provided command here}

**Comment by paul-gauthier** [comment] 2024-08-05 14:10
This looks like a duplicate of #528, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-08-05 14:10 UTC
