### ISSUE TITLE
Feature request: Enable Aider to move (optionally delete) files

### ISSUE THREAD

**Issue by jerzydziewierz** [paul-gauthier/aider#952] opened 2024-07-28 11:32 UTC
### Issue

Aider is great for working with legacy code base, 
i find myself needing to move the files around e.g. to new folders, 
it would be awesome if `aider` knew that he is allowed to "move" files rather than rewriting them verbatim. 

### Version and model info

Aider 0.45.2-dev

**Comment by paul-gauthier** [comment] 2024-07-28 12:24
Thanks for trying aider and filing this issue.

This looks like a duplicate of #528, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-07-28 12:24 UTC
