### ISSUE TITLE
Uncaught ModuleNotFoundError in caching.py line 22

### ISSUE THREAD

**Issue by SmokePigDad** [paul-gauthier/aider#1730] opened 2024-09-25 20:54 UTC
Aider version: 0.57.1
Python version: 3.11.3
Platform: Windows-10-10.0.22635-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.46.1.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 535, in main
    problem = models.sanity_check_models(io, main_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "models.py", line 840, in sanity_check_models
    problem_strong = sanity_check_model(io, main_model)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "models.py", line 873, in sanity_check_model
    possible_matches = fuzzy_match_models(model.name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "models.py", line 889, in fuzzy_match_models
    for model, attrs in litellm.model_cost.items():
                        ^^^^^^^^^^^^^^^^^^
  File "llm.py", line 23, in __getattr__
    self._load_litellm()
  File "llm.py", line 30, in _load_litellm
    self._lazy_module = importlib.import_module("litellm")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "__init__.py", line 9, in <module>
    from litellm.caching import Cache
  File "caching.py", line 22, in <module>
    from openai._models import BaseModel as OpenAIObject
ModuleNotFoundError: No module named 'openai._models'

```

**Comment by fry69** [comment] 2024-09-26 04:54
Thank you for filing this issue.

This looks like something might be broken during installation. Can you please try to install or reinstall aider in a separate Python environment? Either with `venv` or `pipx`?

This document may be helpful -> https://aider.chat/docs/troubleshooting/imports.html

**Comment by paul-gauthier** [comment] 2024-09-27 21:23
Thanks for trying aider and filing this issue.

This looks like a duplicate of #1283. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-09-27 21:23 UTC
Labels: question
