### ISSUE TITLE
Preventing Diff in Commit Messages

### ISSUE THREAD

**Issue by gulliver-madrid** [paul-gauthier/aider#495] opened 2024-03-04 09:32 UTC
Hi,
I have a question regarding the commit messages functionality. Is there a way to prevent diffs from being automatically added to commit messages? I almost always end up squashing multiple commits and deleting the diffs to keep the messages concise.

Thank you for this tool, is awesome!

```
Aider v0.24.1
Model: gpt-4-1106-preview using udiff edit format
```

**Comment by paul-gauthier** [comment] 2024-03-04 19:51
Thanks for trying aider!

This looks like a duplicate of #398 or #352, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-03-04 19:51 UTC
