### ISSUE TITLE
Uncaught AttributeError in sendchat.py line 30

### ISSUE THREAD

**Issue by elsayedmt** [paul-gauthier/aider#1585] opened 2024-09-18 01:49 UTC
Aider version: 0.56.0
Python version: 3.10.8
Platform: macOS-15.0-x86_64-i386-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 24.0.0 (64bit)
Git version: git version 2.46.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "base_coder.py", line 1124, in send_message
    yield from self.send(messages, functions=self.functions)
  File "base_coder.py", line 1413, in send
    raise kbi
  File "base_coder.py", line 1408, in send
    yield from self.show_send_output_stream(completion)
  File "base_coder.py", line 1511, in show_send_output_stream
    self.live_incremental_response(False)
  File "base_coder.py", line 1526, in live_incremental_response
    self.mdstream.update(show_resp, final=final)
  File "mdstream.py", line 78, in update
    console.print(markdown)
  File "console.py", line 1710, in print
    extend(render(renderable, render_options))
  File "console.py", line 1331, in render
    for render_output in iter_render:
  File "markdown.py", line 682, in __rich_console__
    yield from console.render(element, context.options)
  File "console.py", line 1335, in render
    yield from self.render(render_output, _options)
  File "console.py", line 1331, in render
    for render_output in iter_render:
  File "syntax.py", line 620, in __rich_console__
    segments = Segments(self._get_syntax(console, options))
  File "segment.py", line 667, in __init__
    self.segments = list(segments)
  File "syntax.py", line 646, in _get_syntax
    text = self.highlight(processed_code, self.line_range)
  File "syntax.py", line 524, in highlight
    text.append_tokens(
  File "text.py", line 1043, in append_tokens
    for content, style in tokens:
  File "syntax.py", line 524, in <genexpr>
    text.append_tokens(
  File "lexer.py", line 270, in streamer
    for _, t, v in self.get_tokens_unprocessed(text):
  File "lexer.py", line 797, in get_tokens_unprocessed
    m = rexmatch(text, ctx.pos, ctx.end)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 698, in main
    coder.run()
  File "base_coder.py", line 735, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 772, in run_one
    message = self.preproc_user_input(user_message)
  File "base_coder.py", line 761, in preproc_user_input
    return self.commands.run(inp)
  File "commands.py", line 221, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
  File "commands.py", line 196, in do_run
    return cmd_method(args)
  File "commands.py", line 947, in cmd_code
    return self._generic_chat_command(args, self.coder.main_model.edit_format)
  File "commands.py", line 964, in _generic_chat_command
    coder.run(user_msg)
  File "base_coder.py", line 729, in run
    self.run_one(with_message, preproc)
  File "base_coder.py", line 778, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1126, in send_message
    except retry_exceptions() as err:
  File "sendchat.py", line 30, in retry_exceptions
    litellm.llms.anthropic.AnthropicError,
AttributeError: module 'litellm.llms.anthropic' has no attribute 'AnthropicError'

```

**Comment by fry69** [comment] 2024-09-18 02:21
Thank you for filing this issue.

This dependency/import error occurs from installing aider via system packages (or `homebrew`), which do not respect the required dependencies aider needs. Or you may have updated the `LiteLLM` dependency manually.

Please install aider separately from other Python modules, e.g. via `pipx` or `venv`.

This document may be helpful -> https://aider.chat/docs/troubleshooting/imports.html

**Comment by paul-gauthier** [comment] 2024-09-20 18:41
This looks like a duplicate of #1278, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-09-20 18:41 UTC
