### ISSUE TITLE
Files "Not" added to chat

### ISSUE THREAD

**Issue by jamsobes** [paul-gauthier/aider#318] opened 2023-11-02 18:57 UTC
Someone may have noted this but when I ran /ls to get the files added to the chat it said:

**Repo files not in the chat:**

_Basically, it listed all of the files that I DID ADD TO CHAT... doh!_

**Comment by paul-gauthier** [comment] 2023-11-02 22:28
Thanks for trying aider and filing this issue.

I'm not sure I understand the problem you are trying to describe. Maybe can you share a screenshot that shows the issue?

**Comment by nevercast** [comment] 2023-11-02 23:40
Looks alright for me?

```
readme.md> /ls                                                                                                                                                                                                    

Files in chat:

  readme.md

Repo files not in the chat:

  .gitattributes
  .gitignore
  ```

**Comment by jamsobes** [comment] 2023-11-03 01:26
Well, I manually add some files (eg:"/add src/filename.cs"), then when I run the "ls" command it shows everything I added to chat as "not in the chat". In fact nothing shows as "added". 

When I take a look at some of the files in the "aider" git directories, I can see it says "added to chat" in fact when I add them it says this in the console right afterwards... says commit, too... I also tried globbing "/add src/**/*.cs and it rolls through a dozen files as adding them. I think I have about 3 dozen source files altogether.

I do get a throttle message not long after I add too many files within say, 10 mins or so. Some of the files are long but I'm trying to build context so I don't have to explain so much and want it to review things as well.  Does the .DB file keep key value pairs for files and content or am I to add files every single time? I may be doing it wrong as I thought it kept a history/db to eliminate asking for file access every time. 

Maybe I'll just try starting from scratch but a lot of heavy lifting all over again it seems. My code may be terrible, but I spent a lot of hours on it to get the old pile working (my precious), lol.

I'll keep playing with it.

**Comment by paul-gauthier** [comment] 2023-11-03 13:17
Can you share a screenshot?

**Comment by djh00t** [comment] 2023-11-07 13:17
I can..
<img width="1449" alt="Screenshot 2023-11-08 at 00 16 29" src="https://github.com/paul-gauthier/aider/assets/13357567/86534625-1390-4cdf-8bf3-9e151315d7aa">

Hopefully this helps!
I'm running `aider 0.17.0`

**Comment by paul-gauthier** [comment] 2023-11-27 23:08
It looks like maybe you have added some *very large* files to the chat? What does `/tokens` show you? You may have overwhelmed and confused GPT with too much context.

**Comment by paul-gauthier** [comment] 2023-12-05 22:15
Let me know if you can share more info to help debug and reproduce.

I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Closed by paul-gauthier** 2023-12-05 22:15 UTC
Labels: question

**Comment by davidmoshal** [comment] 2023-12-24 00:48
wondering if there is a way to show only files in the chat.
not so useful to have a list of files not in the chat when there are hundreds of files!
