### ISSUE TITLE
[FeatureRequest] Adding lunary via liteLLM as observability / logging / (prompt templating) platform to aider

### ISSUE THREAD

**Issue by lightningRalf** [paul-gauthier/aider#1021] opened 2024-08-06 20:26 UTC
### Issue

How about adding observability and traceability to aider?
based on liteLLM docs it is possible to do: https://docs.litellm.ai/docs/observability/lunary_integration

It can also do so much more: from the readme https://github.com/lunary-ai/lunary
Lunary helps LLM developers take their apps to the next level.

💵 Analytics (cost, token, latency, ..)
🔍 Monitoring (logs, traces, user tracking, ..)
⛩️ Prompt Templates (versioning, team collaboration, ..)
🏷️ Create fine-tuning datasets
🖲️ Chat & feedback tracking
🧪 Evaluations [only enterprise version]

The fine-tuning datasets would be really neat

Thanks in advance for considering.

**Comment by paul-gauthier** [comment] 2024-08-07 15:54
This looks like a duplicate of #976, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-08-07 15:54 UTC

**Comment by lightningRalf** [comment] 2024-08-09 11:11
Sorry I did not find the above issue.
I think there are multiple requests in mine. So monitoring and analytics are the dublication of issue #976 

But the prompt templating and fine-tuning datasets posibilities are seperate issues I would say. 
The reason why everything is in one place is, because the functionality could be developed one after another, and to do that, we need lunary first.
