### ISSUE TITLE
How to activate a project environment when using /run?

### ISSUE THREAD

**Issue by ProgramItUp** [paul-gauthier/aider#337] opened 2023-11-09 16:32 UTC
I have a Conda environment for my project called project_env with all of the packages installed that are needed by the project.
How can it be activated before executing my code?

Here is what I would like to do

`/run conda activate project_env; python main.py`

but it does not work.

```
/run conda activate project_env; python main.py

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
```
It tried running `conda init bash ` but it does not doesn't help.

```
/run conda init bash; conda activate trend_analyzer; python main.py

no change     /home/me/anaconda3/condabin/conda
no change     /home/me/anaconda3/bin/conda
no change     /home/me/anaconda3/bin/conda-env
no change     /home/me/anaconda3/bin/activate
no change     /home/me/anaconda3/bin/deactivate
no change     /home/me/anaconda3/etc/profile.d/conda.sh
no change     /home/me/anaconda3/etc/fish/conf.d/conda.fish
no change     /home/me/anaconda3/shell/condabin/Conda.psm1
no change     /home/me/anaconda3/shell/condabin/conda-hook.ps1
no change     /home/me/anaconda3/lib/python3.9/site-packages/xontrib/conda.xsh
no change     /home/me/anaconda3/etc/profile.d/conda.csh
no change     /home/me/.bashrc
No action taken.

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.

Traceback (most recent call last):
  File "/home/me/code/project_env/main.py", line 4, in <module>
    from openai_summarizer import summarize_article
  File "/home/me/code/project_env/openai_summarizer.py", line 2, in <module>
        import feedparser
ModuleNotFoundError: No module named 'feedparser'
```

**Comment by ProgramItUp** [comment] 2023-11-10 22:31
Is it possible for a conda environment to be activated during a /run?
Thanks.

**Comment by SunnyOd** [comment] 2023-11-14 19:29
try to source conda.sh before activating the env:
  `source /etc/profile.d/conda.sh`

might work not sure though

**Comment by paul-gauthier** [comment] 2023-11-14 19:36
Thanks for trying aider and filing this issue.

Whatever shell environment is active when you run aider should still be active for the commands that are `/run` from inside aider. So try activating your python environment before running aider?

**Comment by paul-gauthier** [comment] 2023-11-21 21:46
I'm going to close this issue for now, but feel free to reopen it or open a new issue if you have more to discuss.

**Closed by paul-gauthier** 2023-11-21 21:46 UTC
Labels: question

**Comment by ktakanopy** [comment] 2024-12-06 18:48
Hi, does anyone know how to activate environment inside aider? conda activate not works. Thanks in advance

**Comment by tenebrius** [comment] 2025-02-02 06:38
> Thanks for trying aider and filing this issue.
> 
> Whatever shell environment is active when you run aider should still be active for the commands that are `/run` from inside aider. So try activating your python environment before running aider?

I am opening aider from inside my conda environment, but the python version does not match, nor are my env packages available

**Comment by husnoo** [comment] 2025-05-14 19:04
the problem is that aider seems to require a certain version of python and most projects will have some different version of python that can be used (e.g. if you already have cuda/torch installed in a different env).

in bash, I use subshell and conda activate before running code - maybe aider can do that, or call out a shell script or something to get to the code being run.
