### ISSUE TITLE
Uncaught TypeError in repomap.py line 665

### ISSUE THREAD

**Issue by KishoreBNandana** [paul-gauthier/aider#1738] opened 2024-09-26 05:23 UTC
Aider version: <module 'aider.__version__' from '/opt/homebrew/lib/python3.11/site-packages/aider/__version__.py'>
Python version: 3.11.9
Platform: macOS-14.6.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.39.3 (Apple Git-146)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 709, in main
    coder.run()
  File "base_coder.py", line 723, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 766, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1097, in send_message
    chunks = self.format_messages()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1035, in format_messages
    chunks = self.format_chat_chunks()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 985, in format_chat_chunks
    chunks.repo = self.get_repo_messages()
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 620, in get_repo_messages
    repo_content = self.get_repo_map()
                   ^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 602, in get_repo_map
    repo_content = self.repo_map.get_repo_map(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 127, in get_repo_map
    files_listing = self.get_ranked_tags_map(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 478, in get_ranked_tags_map
    result = self.get_ranked_tags_map_uncached(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 509, in get_ranked_tags_map_uncached
    ranked_tags = self.get_ranked_tags(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 342, in get_ranked_tags
    tags = list(self.get_tags(fname, rel_fname))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 198, in get_tags
    data = list(self.get_tags_raw(fname, rel_fname))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 221, in get_tags_raw
    query_scm = get_scm_fname(lang)
                ^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 665, in get_scm_fname
    return resources.files(__package__).joinpath("queries", f"tree-sitter-{lang}-tags.scm")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MultiplexedPath.joinpath() takes 2 positional arguments but 3 were given

```

**Comment by fry69** [comment] 2024-09-26 05:24
Thank you for filing this issue.

This looks like something might be broken during installation. Can you please try to install or reinstall aider in a separate Python environment? Either with `venv` or `pipx`?

This document may be helpful -> https://aider.chat/docs/troubleshooting/imports.html

**Comment by paul-gauthier** [comment] 2024-09-27 21:29
Thanks for trying aider and filing this issue.

This looks like a duplicate of #1665. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-09-27 21:29 UTC
Labels: question
