### ISSUE TITLE
Uncaught AttributeError in sendchat.py line 30

### ISSUE THREAD

**Issue by bluchip6** [paul-gauthier/aider#1557] opened 2024-09-15 23:30 UTC
Aider version: 0.56.0
Python version: 3.10.11
Platform: Windows-10-10.0.19045-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.30.0.windows.2

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 7, in <module>
    sys.exit(main())
  File "main.py", line 698, in main
    coder.run()
  File "base_coder.py", line 735, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 778, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1202, in send_message
    saved_message = self.auto_commit(edited)
  File "base_coder.py", line 1885, in auto_commit
    res = self.repo.commit(fnames=edited, context=context, aider_edits=True)
  File "repo.py", line 102, in commit
    commit_message = self.get_commit_message(diffs, context)
  File "repo.py", line 187, in get_commit_message
    commit_message = simple_send_with_retries(
  File "sendchat.py", line 38, in wrapper
    retry_exceptions(),
  File "sendchat.py", line 30, in retry_exceptions
    litellm.llms.anthropic.AnthropicError,
AttributeError: module 'litellm.llms.anthropic' has no attribute 'AnthropicError'

```

**Comment by fry69** [comment] 2024-09-16 04:30
Thank you for filing this issue.

Please install aider separately from all other Python modules, as it needs specific versions. At best use `pipx` to let it manage the aider `venv` for you.

The error you see comes from the fact that you installed a newer LiteLLM version than aider supports (currently `1.44.7`).

This doc may be helpful -> https://aider.chat/docs/troubleshooting/imports.html

**Comment by Liu-Eroteme** [comment] 2024-09-16 18:02
Same issue on my nix machine here - aider installed via nix unstable.aider-chat

**Comment by fry69** [comment] 2024-09-16 18:45
System packages sadly often get the dependencies wrong. Please find another way to install aider, `pipx` is known to work reliably.

**Comment by alexanderkjeldaas** [comment] 2024-09-17 12:13
Same issue on nix.

**Comment by fry69** [comment] 2024-09-17 12:20
These dependency/import error occur from installing aider via system packages, which do not respect the required dependencies aider needs.

Please install aider via `pipx` or `venv`.

This document may be helpful -> https://aider.chat/docs/troubleshooting/imports.html

Thank you.

**Comment by alexanderkjeldaas** [comment] 2024-09-17 12:23
The reporters here are using nix to manage versioning and global state on their computers.  nixpkgs can build packages in various ways either using system packages, or converting existing dependencies into wrapped system packages etc.  The inclusion of aider-chat into nixpkgs is quite fresh so maybe a solution can be found.  This shouldn't be the only package among the 100.000 packages in nixpkgs that has this issue, so probably this can just be fixed.

**Comment by alexanderkjeldaas** [comment] 2024-09-17 12:25
Ah, I see that the original reporter was not using nix.  Anyways for the nix-specific issue, I hope this can be solvable in nixpkgs.

**Comment by paul-gauthier** [comment] 2024-09-20 18:41
This looks like a duplicate of #1278, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-09-20 18:41 UTC
