### ISSUE TITLE
Config file docs

### ISSUE THREAD

**Issue by andreasciamanna** [paul-gauthier/aider#121] opened 2023-07-18 08:06 UTC
Hi!

I know I can create a `.aider.conf.yml`, but either I'm terrible at searching here and in the codebase, or there is no documentation about this file.

For instance, for some reason, Aider tries to commit `node_modules` (failing because Git is set to prevent this), even if it's in the `.gitignore` file.
I hoped I could force Aider to ignore that directory through the config file (or an argument, but there isn't such an argument).

But I'm also curious about what other parameters I can store there to include them as part of the project.

Thanks,
Andrea

**Comment by paul-gauthier** [comment] 2023-07-18 15:16
Thanks for trying aider!

I am surprised that you say aider adding `node_modules` to git. Can you show me some of the output where that happens? Aider is only supposed to add files to git if you `/add` them to the chat session. And there should be no way to add any files to git which appear in `.gitignore`.

If you run `aider --help` it will list all of the options. The last few lines explain how to specify them in a config yml file:

```
Args that start with '--' (eg. --openai-api-key) can also be set in a config file (/Users/gauthier/Projects/aider/.aider.conf.yml or /Users/gauthier/.aider.conf.yml or specified via -c). The config file uses YAML syntax and must represent a YAML 'mapping'
(for details, see http://learn.getgrav.org/advanced/yaml). If an arg is specified in more than one place, then commandline values override environment variables which override config file values which override defaults.
```

**Comment by paul-gauthier** [comment] 2023-07-19 12:12
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Comment by andreasciamanna** [comment] 2023-07-27 07:39
Sorry for the late reply.

> Thanks for trying aider!

Thanks to you for it!

> I am surprised that you say aider adding `node_modules` to git. Can you show me some of the output where that happens? Aider is only supposed to add new files to git if you `/add` them to the chat session or specify them on the command line. And there should be no way to add any files to git which appear in `.gitignore`.

It's a very long output and it seems to happen only on a specific project (a YouTrack Workflow rules project set up according to this documentation).

That's an excerpt:

```
Git repo has uncommitted changes.
Commit before the chat proceeds [y/n/commit message]? Adjust comments visibility from reviewers in cron job and onChange event.

Traceback (most recent call last):
  File "/Users/%USER%/anaconda3/bin/aider", line 8, in <module>
    sys.exit(main())
  File "/Users/%USER%/anaconda3/lib/python3.10/site-packages/aider/main.py", line 447, in main
    coder.commit(ask=True, which="repo_files")
  File "/Users/%USER%/anaconda3/lib/python3.10/site-packages/aider/coders/base_coder.py", line 930, in commit
    repo.git.add(*relative_dirty_fnames)
  File "/Users/%USER%/anaconda3/lib/python3.10/site-packages/git/cmd.py", line 741, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/Users/%USER%/anaconda3/lib/python3.10/site-packages/git/cmd.py", line 1315, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/Users/%USER%/anaconda3/lib/python3.10/site-packages/git/cmd.py", line 1109, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git add .eslintignore .eslintrc.json .gitignore .gitlab-ci.yml .idea/.gitignore .idea/codeStyles/codeStyleConfig.xml .idea/inspectionProfiles/Project_Default.xml .idea/jsLibraryMappings.xml .idea/jsLinters/eslint.xml .idea/modules.xml .idea/prettier.xml .idea/vcs.xml .idea/youtrack-workflows.iml .prettierrc README.md forum-tickets-count/README.md forum-tickets-count/cron-update-escalated-tickets-forums-count.js forum-tickets-count/cron-update-escalations-forums-count.js forum-tickets-count/forum-threads.js forum-tickets-count/manifest.json forum-tickets-count/update-forums-count.js forum-tickets-count/update-priority.js node_modules/.bin/cross-env node_modules/.bin/cross-env-shell node_modules/.bin/mkdirp node_modules/.bin/node-which node_modules/.bin/rimraf node_modules/.bin/youtrack-workflow node_modules/@jetbrains/youtrack-scripting-api/.nvmrc node_modules/@jetbrains/youtrack-scripting-api/LICENSE.txt node_modules/@jetbrains/youtrack-scripting-api/README.md node_modules/@jetbrains/youtrack-scripting-api/cache.js 
// ... it keeps going ...
  stderr: 'The following paths are ignored by one of your .gitignore files:
node_modules
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"'
```

Then it exits aider (0.10.1), and no commit is made.

> If you run `aider --help` it will list all of the options. The last few lines explain how to specify them in a config yml file:
> 
> ```
> Args that start with '--' (eg. --openai-api-key) can also be set in a config file (/Users/gauthier/Projects/aider/.aider.conf.yml or /Users/gauthier/.aider.conf.yml or specified via -c). The config file uses YAML syntax and must represent a YAML 'mapping'
> (for details, see http://learn.getgrav.org/advanced/yaml). If an arg is specified in more than one place, then commandline values override environment variables which override config file values which override defaults.
> ```

I completely missed that. 

Thanks!

**Comment by paul-gauthier** [comment] 2023-07-28 14:39
The latest version of aider in the main github branch has changed the logic used when doing "dirty commits". You might wand to try installing that to see if the issue you're reporting is resolved. I think it should be.

This is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by joshuavial** [comment] 2023-08-01 04:28
I've done a bit of testing and was able to reproduce something in this direction

- checkout git main aider branch
- deleted .aider files
- checked in gitignore
- started aider a few times and ignored the prompt to add aider
- added .aider files to git

at this stage every time I started aider it would prompt me to save the updates to the log file that were written by that start

- deleted .aider files from git with a git rm on the command line. I didn't commit the changes
- launched aider and it blew up with .aider.input.history did not match any file


https://github.com/paul-gauthier/aider/compare/main...joshuavial:aider:git-tests has the git log

---

Git repo has uncommitted changes.
Commit before the chat proceeds [y/n/commit message]? Deleted .aider.chat.history.md and .aider.input.history files.

Traceback (most recent call last):
  File "/home/jv/miniconda3/bin/aider", line 8, in <module>
    sys.exit(main())
  File "/home/jv/miniconda3/lib/python3.10/site-packages/aider/main.py", line 447, in main
    coder.commit(ask=True, which="repo_files")
  File "/home/jv/miniconda3/lib/python3.10/site-packages/aider/coders/base_coder.py", line 930, in commit
    repo.git.add(*relative_dirty_fnames)
  File "/home/jv/.local/lib/python3.10/site-packages/git/cmd.py", line 741, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/jv/.local/lib/python3.10/site-packages/git/cmd.py", line 1315, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/jv/.local/lib/python3.10/site-packages/git/cmd.py", line 1109, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git add .aider.chat.history.md .aider.input.history .dockerignore .flake8 .github/workflows/release.yml .github/workflows/ubuntu-tests.yml .github/workflows/windows-tests.yml .gitignore .pre-commit-config.yaml CNAME HISTORY.md LICENSE.txt MANIFEST.in README.md _config.yml _layouts/default.html aider/__init__.py aider/coders/__init__.py aider/coders/base_coder.py aider/coders/base_prompts.py aider/coders/editblock_coder.py aider/coders/editblock_func_coder.py aider/coders/editblock_func_prompts.py aider/coders/editblock_prompts.py aider/coders/single_wholefile_func_coder.py aider/coders/single_wholefile_func_prompts.py aider/coders/wholefile_coder.py aider/coders/wholefile_func_coder.py aider/coders/wholefile_func_prompts.py aider/coders/wholefile_prompts.py aider/commands.py aider/diffs.py aider/dump.py aider/history.py aider/io.py aider/main.py aider/models.py aider/prompts.py aider/repo.py aider/repomap.py aider/sendchat.py aider/utils.py aider/versioncheck.py assets/benchmarks.svg assets/css/style.scss assets/figure.png assets/robot-flowchart.png assets/screencast.svg assets/screenshot.png benchmark/Dockerfile benchmark/__init__.py benchmark/benchmark.py benchmark/docker.sh benchmark/docker_build.sh benchmark/plot.sh benchmark/prompts.py benchmark/rungrid.py benchmark/test_benchmark.py docs/benchmarks.md docs/commands.md docs/ctags.md docs/faq.md docs/install.md examples/2048-game.md examples/README.md examples/add-test.md examples/asciinema.md examples/census.md examples/chat-transcript-css.md examples/complex-change.md examples/css-exercises.md examples/hello-world-flask.md examples/hello.md examples/no-color.md examples/pong.md examples/semantic-search-replace.md examples/update-docs.md pytest.ini requirements.txt scripts/versionbump.py setup.py tests/__init__.py tests/test_coder.py tests/test_commands.py tests/test_editblock.py tests/test_io.py tests/test_main.py tests/test_models.py tests/test_repo.py tests/test_repomap.py tests/test_sendchat.py tests/test_wholefile.py tests/utils.py
  stderr: 'fatal: pathspec '.aider.input.history' did not match any files'

**Comment by andreasciamanna** [comment] 2023-08-01 08:26
Hi.

Sorry if I'm always late with my answers, but I need to wait until I catch the error which I just did.

For good measure, I've updated Aider again using `python -m pip install git+https://github.com/paul-gauthier/aider.git` and it shows it's now at version `0.10.1`.

Starting aider on a project with a dirty commit, I get asked if I want to commit, and I even get the commit message as expected, but then it throws an error before exiting:

```
(base) ➜  my-project git:(master) ✗ aider
Aider v0.10.1
Model: gpt-4
Git repo: .git
Repo-map: universal-ctags using 1024 tokens
diff --git a/src/app/components/navigation/RouteElementMenu.tsx b/src/app/components/navigation/RouteElementMenu.tsx
deleted file mode 100644
index c12964a..0000000
--- a/src/app/components/navigation/RouteElementMenu.tsx
+++ /dev/null
@@ -1,57 +0,0 @@
-import { Collapse, Divider, MenuItemProps } from '@mui/material';
-import * as React from 'react';
-import { FC, ReactNode } from 'react';
-import { RouteDefinition } from '../../routing/types';
-import AuthorizedListItem from '../wrappers/AuthorizedListItem';
-
-type RouteElementMenuProps = {
-  definition: RouteDefinition;
-  nesting?: number;
-};
-
-export const RouteElementMenu: FC<RouteElementMenuProps> = ({
-  definition,
-  nesting = 0,
-}) => {
-  if (definition.hideFromMenu) return null;
-
-  if (definition.renderAsCustomListItem) {
-    const Component =
-      definition.renderAsCustomListItem as React.ComponentType<MenuItemProps>; // or specific props type
-    return <Component disabled={definition.disableInMenu} />;
-  }
-
-  let children: ReactNode;
-  if (definition.children && definition.children.length > 0) {
-    children = (
-      <>
-        <Collapse in={true}>
-          {definition.children.map((item, key) => (
-            <RouteElementMenu
-              definition={item}
-              nesting={nesting + 1}
-              key={key}
-            />
-          ))}
-        </Collapse>
-        <Divider />
-      </>
-    );
-  }
-
-  return (
-    <>
-      {(definition.startWithDivider || definition.children) && <Divider />}
-      <AuthorizedListItem
-        sx={{ pl: nesting }}
-        icon={definition.icon}
-        label={definition.label}
-        to={definition.route}
-        allowedRoles={definition.allowedRoles}
-        disabled={definition.disableInMenu}
-      />
-      {children}
-      {definition.endWithDivider && <Divider />}
-    </>
-  );
-};
diff --git a/src/app/routing/definitions.tsx b/src/app/routing/definitions.tsx
index 4d87382..6e40fd6 100644
--- a/src/app/routing/definitions.tsx
+++ b/src/app/routing/definitions.tsx
@@ -1,4 +1,3 @@
-import * as React from 'react';
 import { RouteLabels, RoutePaths } from './types';

 export const routePaths: RoutePaths = {
diff --git a/src/app/routing/types.ts b/src/app/routing/types.ts
index 884c315..17e3b82 100644
--- a/src/app/routing/types.ts
+++ b/src/app/routing/types.ts
@@ -1,9 +1,3 @@
-import { ListItemProps } from '@mui/material';
-import * as React from 'react';
-import { ElementType } from 'react';
-import { RouteProps } from 'react-router-dom';
-import { UserEntity } from '../../services/rest';
-
 enum RouteKeys {
   HOME,
   LOGIN,
@@ -25,20 +19,3 @@ export type RoutePaths = {
 export type RouteLabels = {
   [key in RouteLabelsType]: string;
 };
-
-export type RouteDefinition = {
-  hideFromMenu?: boolean;
-  disableInMenu?: boolean;
-  hideFromBreadCrumb?: boolean;
-  icon?: ElementType;
-  label: RouteLabels[RouteLabelsType];
-  childrenParam?: string;
-  route?: RoutePaths[RoutePathsType];
-  children?: RouteDefinition[];
-  showCondition?: () => boolean;
-  allowedRoles?: UserEntity.role[];
-  renderAsCustomListItem?: React.ComponentType<ListItemProps>;
-  startWithDivider?: boolean;
-  endWithDivider?: boolean;
-  element?: RouteProps['element'];
-};

Git repo has uncommitted changes.
Commit before the chat proceeds [y/n/commit message]? Deleted RouteElementMenu component and removed unused
 imports and types from routing files.

Traceback (most recent call last):
  File "/opt/homebrew/bin/aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/aider/main.py", line 447, in main
    coder.commit(ask=True, which="repo_files")
  File "/opt/homebrew/lib/python3.11/site-packages/aider/coders/base_coder.py", line 930, in commit
    repo.git.add(*relative_dirty_fnames)
  File "/opt/homebrew/lib/python3.11/site-packages/git/cmd.py", line 741, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/git/cmd.py", line 1315, in _call_process
    return self.execute(call, **exec_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/git/cmd.py", line 1109, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git add .browserslistrc .eslintignore .eslintrc.json .gitignore .husky/commit-msg .nvmrc .prettierignore .prettierrc .versionrc.js CHANGELOG.md README.md commitlint.config.js e2e/.eslintrc.json e2e/cypress.config.ts e2e/project.json e2e/src/e2e/app.cy.ts e2e/src/fixtures/example.json e2e/src/support/app.po.ts e2e/src/support/commands.ts e2e/src/support/e2e.ts e2e/tsconfig.json example.env index.html nx.json package-lock.json package.json project.json public/VERSION.txt public/favicon.ico src/_versions.ts src/app/app.module.scss src/app/components/Chat.tsx src/app/components/DocumentContent.tsx src/app/components/DocumentSide.tsx src/app/components/ErrorMessage.tsx src/app/components/ListItemLink.tsx src/app/components/Message.tsx src/app/components/NewSession.tsx src/app/components/NewUserMessage.tsx src/app/components/RoleGridEdit.tsx src/app/components/SelectModel.tsx src/app/components/Shield.tsx src/app/components/StatsDisplay.tsx src/app/components/actions/DocumentActions.tsx src/app/components/actions/FormActions.tsx src/app/components/actions/LongTextCellEdit.tsx src/app/components/actions/datasetEntries/AddNew.tsx src/app/components/actions/datasetEntries/DeleteEntry.tsx src/app/components/actions/datasetEntries/DeleteManyEntries.tsx src/app/components/actions/datasetEntries/EditEntry.tsx src/app/components/actions/datasetEntries/GridActions.tsx src/app/components/actions/datasetEntries/GridToolbar.tsx src/app/components/actions/datasetEntries/RecoverEntry.tsx src/app/components/actions/datasetEntries/ToggleTrashed.tsx src/app/components/actions/datasetEntries/UploadJSONL.tsx src/app/components/actions/training/GridToolbar.tsx src/app/components/actions/training/action-cell/Edit.tsx src/app/components/actions/training/action-cell/Open.tsx src/app/components/actions/training/action-cell/Process.tsx src/app/components/actions/training/action-cell/Sign.tsx src/app/components/actions/training/action-cell/Take.tsx src/app/components/actions/tuningBatches/Delete.tsx src/app/components/actions/tuningBatches/Edit.tsx src/app/components/actions/tuningBatches/GridActions.tsx src/app/components/actions/tuningBatches/GridToolbar.tsx src/app/components/actions/types.ts src/app/components/buttons/AnalyzeDataset.tsx src/app/components/buttons/ButtonWithConfirmation.tsx src/app/components/buttons/ButtonWithConfirmationAndOptionstInput.tsx src/app/components/buttons/ButtonWithConfirmationAndTextInput.tsx src/app/components/buttons/CancelJob.tsx src/app/components/buttons/ColorModeToggle.tsx src/app/components/buttons/FontSize.tsx src/app/components/buttons/Logout.tsx src/app/components/buttons/MenuButton.tsx src/app/components/buttons/Rate.tsx src/app/components/buttons/RefreshJob.tsx src/app/components/buttons/SubmitJob.tsx src/app/components/buttons/ToolsButton.tsx src/app/components/container/AppContainer.tsx src/app/components/container/MainContainer.tsx src/app/components/data/Approvals.tsx src/app/components/data/DocumentDetails.tsx src/app/components/data/DocumentLabel.tsx src/app/components/data/DocumentLabels.tsx src/app/components/data/EditTraining.tsx src/app/components/data/EditTrainingFormContent.tsx src/app/components/data/FineTuneModelName.tsx src/app/components/data/FineTuneModelSummary.tsx src/app/components/data/GridCellExpand.tsx src/app/components/data/LastJobStatus.tsx src/app/components/data/OpenAIJobsStatus.tsx src/app/components/data/SessionSettings.tsx src/app/components/data/SmallBadge.tsx src/app/components/data/SuggestedLabel.tsx src/app/components/data/Tokens.tsx src/app/components/data/TrainingGrid.tsx src/app/components/data/TrainingTimeline.tsx src/app/components/data/Trainings.tsx src/app/components/data/UserName.tsx src/app/components/dialogs/ConfirmationDialog.tsx src/app/components/feed/DatasetEntries.tsx src/app/components/feed/Sessions.tsx src/app/components/feed/StripedDataGrid.tsx src/app/components/feed/dataGridHelpers.ts src/app/components/feedback/FormikErrorMessage.tsx src/app/components/icons/OTGSLogo.tsx src/app/components/icons/OpenAI.tsx src/app/components/inputs/AIAgent.tsx src/app/components/inputs/EditableText.tsx src/app/components/inputs/NewDocumentLabel.tsx src/app/components/inputs/NewMessage.tsx src/app/components/inputs/SelectModel.tsx src/app/components/inputs/SelectModelConfig.tsx src/app/components/inputs/TrainingCategory.tsx src/app/components/navigation/AppHeader.tsx src/app/components/navigation/AppMenu.tsx src/app/components/navigation/AppRoutes.tsx src/app/components/navigation/Breadcrumbs.tsx src/app/components/navigation/Crumb.tsx src/app/components/navigation/Documents.tsx src/app/components/navigation/DrawerHeader.tsx src/app/components/navigation/LinkRouter.tsx src/app/components/navigation/LoginMenuItem.tsx src/app/components/navigation/RouteElementMenu.tsx src/app/components/navigation/Tools.tsx src/app/components/screens/Documents.tsx src/app/components/screens/FineTuneModel.tsx src/app/components/screens/FineTuneModels.tsx src/app/components/screens/GoogleCallback.tsx src/app/components/screens/Home.tsx src/app/components/screens/Login.tsx src/app/components/screens/NoMatch.tsx src/app/components/screens/OpenAIModels.tsx src/app/components/screens/Playground.tsx src/app/components/screens/Profile.tsx src/app/components/screens/TuningBatch.tsx src/app/components/screens/TuningBatches.tsx src/app/components/screens/Unauthorized.tsx src/app/components/screens/Users.tsx src/app/components/types.tsx src/app/components/wrappers/ApprovalsConsole.tsx src/app/components/wrappers/AuthorizedListItem.tsx src/app/components/wrappers/TrainingsConsole.tsx src/app/components/wrappers/withAuthorization.tsx src/app/features/authSlice.ts src/app/features/chatSlice.ts src/app/features/datasetEntriesSlice.ts src/app/features/documentFeedbackSlice.ts src/app/features/documentSlice.ts src/app/features/fineTuneModelsSlice.ts src/app/features/fineTuningSlice.ts src/app/features/middleware.ts src/app/features/sessionsSlice.ts src/app/features/trainingSlice.ts src/app/features/tuningBatchesSlice.ts src/app/features/types.ts src/app/features/usersSlice.ts src/app/hooks.ts src/app/providers/AuthProvider.tsx src/app/providers/TrainingsProvider.tsx src/app/providers/UserThemeProvider.tsx src/app/routing/definitions.tsx src/app/routing/types.ts src/app/store.ts src/assets/.gitkeep src/constants.ts src/env.d.ts src/helpers/documents.ts src/helpers/jobs.ts src/helpers/pre-sales.ts src/hooks/useDocument.tsx src/hooks/useFontSize.tsx src/hooks/useQuery.tsx src/hooks/useRole.tsx src/main.tsx src/mui.d.ts src/services/rest/core/ApiError.ts src/services/rest/core/ApiRequestOptions.ts src/services/rest/core/ApiResult.ts src/services/rest/core/CancelablePromise.ts src/services/rest/core/OpenAPI.ts src/services/rest/core/request.ts src/services/rest/index.ts src/services/rest/models/ArchiveTrainingDto.ts src/services/rest/models/ChangeUserRoleDto.ts src/services/rest/models/CreateDatasetEntryDto.ts src/services/rest/models/CreateDocumentDto.ts src/services/rest/models/CreateDocumentFeedbackDto.ts src/services/rest/models/CreateDocumentLabelDto.ts src/services/rest/models/CreateJobDto.ts src/services/rest/models/CreateModelConfigurationDto.ts src/services/rest/models/CreateSessionDto.ts src/services/rest/models/DatasetEntryEntity.ts src/services/rest/models/DeleteModelResponseDto.ts src/services/rest/models/DocumentEntity.ts src/services/rest/models/DocumentFeedbackEntity.ts src/services/rest/models/DocumentLabelEntity.ts src/services/rest/models/GetUserDocumentFeedbackDto.ts src/services/rest/models/JobEntity.ts src/services/rest/models/JobValidationResponse.ts src/services/rest/models/LabelEntity.ts src/services/rest/models/ModelConfigurationEntity.ts src/services/rest/models/ModelEntity.ts src/services/rest/models/RemoveLabelDto.ts src/services/rest/models/ReviewTrainingDto.ts src/services/rest/models/SessionEntity.ts src/services/rest/models/SignPayload.ts src/services/rest/models/SyntheticDocumentDto.ts src/services/rest/models/TrainingEntity.ts src/services/rest/models/TrainingJobDto.ts src/services/rest/models/UpdateDatasetEntryDto.ts src/services/rest/models/UpdateDocumentDto.ts src/services/rest/models/UpdateDocumentFeedbackDto.ts src/services/rest/models/UpdateJobDto.ts src/services/rest/models/UpdateModelConfigurationDto.ts src/services/rest/models/UpdateSessionDto.ts src/services/rest/models/UserDocumentFeedbackDto.ts src/services/rest/models/UserEntity.ts src/services/rest/models/UserStats.ts src/services/rest/services/AuthService.ts src/services/rest/services/DatasetEntryService.ts src/services/rest/services/DocumentFeedbackService.ts src/services/rest/services/DocumentService.ts src/services/rest/services/FineTuningService.ts src/services/rest/services/JobsService.ts src/services/rest/services/LabelService.ts src/services/rest/services/ModelConfigurationService.ts src/services/rest/services/ModelsService.ts src/services/rest/services/SessionsService.ts src/services/rest/services/TrainingService.ts src/services/rest/services/UserManagementService.ts src/socket.ts src/styles.scss tsconfig.app.json tsconfig.json tsconfig.spec.json vite.config.ts
  stderr: 'fatal: pathspec 'src/app/components/navigation/RouteElementMenu.tsx' did not match any files'
(base) ➜  my-project git:(master) ✗
```


The problem goes away if I do a manual commit, then I can use aider with no problem until it decides to crash again.

On a different project (the YouTrack Workflow one [mentioned here](https://github.com/paul-gauthier/aider/issues/121#issuecomment-1653068390)), which, unfortunately, I don't touch very often, the problem seems to happen on every change.

**Comment by joshuavial** [comment] 2023-08-02 22:37
yeah, it was a manual git add - just messing around to see if I could replicate some kind of similar error. 

I think we're always going to see some users who inadvertently add aider files to git - maybe we handle it with a warning message similar to the 'a new version is released' one if the files are in git and warn that aider will behave unpredictably in that situation.

I don't have any immediate ideas about how to rule out that aider is somehow causing the files to be added. I haven't observed that behaviour. Maybe a tail end warning to the user (or additional logging) if we detect a file being committed which has a . prefix would help catch it if it's happening in the wild?

**Comment by paul-gauthier** [comment] 2023-08-03 11:37
@joshuavial thanks for trying to reproduce and debug this issue. I really appreciate the second set of eyes on it. I also concluded that the only way this could be happening is if the users are doing the `git add` themselves.

I may end up moving the whole commit system to only committing the files which have been added to the chat. It's not ideal, because GPT could base its changes on other repo files which are dirty which never actually get commited by the user in their current state.

**Comment by andreasciamanna** [comment] 2023-08-03 12:31
> Hi @andreasciamanna, unfortunately, it doesn't look like you succeeded in upgrading to the aider version from the main branch. It would have announced version `v0.10.2-dev`. And your stack trace agrees, it is showing older code.

Indeed. A bit of a mess with the environment (and a lack of understanding of dependencies management in Python) caused me to believe I had upgraded.

I see now there is a 0.11 version and upgraded.

I'll check if I still get the errors, but so far it all looks good.

**Comment by joshuavial** [comment] 2023-08-03 22:05
> I may end up moving the whole commit system to only committing the files which have been added to the chat. It's not ideal, because GPT could base its changes on other repo files which are dirty which never actually get commited by the user in their current state.

I wonder about a strategy of 
- check status of each file ChatGPT wants to update
- complain if any are dirty or not in git and require user intervention - maybe give the user the options to 
a) add/commit before changing 
b) change anyway 
c) abort

that would mean we could ditch the whole dirty check on startup which takes a while to get used to and give users more flexibility overall

**Comment by paul-gauthier** [comment] 2023-08-14 16:46
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Closed by paul-gauthier** 2023-08-14 16:46 UTC
Labels: question
