### ISSUE TITLE
allow aider to run commands, that are written by the LLM itself.

### ISSUE THREAD

**Issue by Kreijstal** [paul-gauthier/aider#1114] opened 2024-08-17 19:19 UTC
### Issue

in case it needs to do one time off things, of course we can edit and approve the commands it suggests

### Version and model info

claude 3.5

**Comment by SShadowS** [comment] 2024-08-19 13:28
![image](https://github.com/user-attachments/assets/108b817a-e8e9-434f-bb7d-8e5672116827)
Try using the help

**Comment by Kreijstal** [comment] 2024-08-19 13:59
> ![image](https://private-user-images.githubusercontent.com/3491765/359117718-108b817a-e8e9-434f-bb7d-8e5672116827.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNzYxNTQsIm5iZiI6MTcyNDA3NTg1NCwicGF0aCI6Ii8zNDkxNzY1LzM1OTExNzcxOC0xMDhiODE3YS1lOGU5LTQzNGYtYmI3ZC04ZTU2NzIxMTY4MjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTlUMTM1NzM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDk0ZGE4NTQzNTgwODQzMzk4YzRlODA3YTFhOTMxNjQyOWM2MTdmYmYzOTgyNDM4MWUyMTQ3Nzk3MzgxMjNhZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AgEc_uL2oDSLSbW7exirhJGTRi38ClSjw-IGs86Fq6A) Try using the help

Yes but I have to type the command myself?, Can you tell it to do `/run write a command that greps the string in this directory?`

**Comment by Kreijstal** [comment] 2024-08-19 14:02
Seems like there isnt a command that lets the LLM run commands itself. Which is the point of the issue.

**Comment by SShadowS** [comment] 2024-08-19 14:06
You wrote Aider. And Aider runs a command with /run
I guess you want the LLM output to be parsed it into a prompt itself (Super dangerous, but ok). But not what you asked about. :)

**Comment by Kreijstal** [comment] 2024-08-19 14:08
> You wrote Aider. And Aider runs a command with /run I guess you want the LLM output to be parsed it into a prompt itself (Super dangerous, but ok). But not what you asked about. :)

but I said " of course we can edit and approve the commands it suggests", and sure there is https://github.com/OpenInterpreter/open-interpreter but that one doesn't edit files.

**Comment by SShadowS** [comment] 2024-08-19 15:02
You could make it edit the same file you have set as the test file in .env
Like RunScript.sh and add it to the context. Then you just need to press /test

**Comment by sholub89** [comment] 2024-08-19 16:12
I was looking for a somewhat similar feature that would be extremely helpful in scripting. For example, Aiders makes the change, to make sure all is fine - it could execute the build command, etc. There are workarounds, but would be amazing if Aider could do it himself.

**Comment by SShadowS** [comment] 2024-08-19 16:38
It builds automatically here. I just have build in the test command and then set it to auto test.

**Comment by sholub89** [comment] 2024-08-19 16:43
> It builds automatically here. I just have build in the test command and then set it to auto test.

Good idea. I will try doing the same

**Comment by paul-gauthier** [comment] 2024-08-19 18:57
Thanks for trying aider and filing this issue.

This looks like a duplicate of #528, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-08-19 18:57 UTC
