### ISSUE TITLE
Continuing after token limit cutoff

### ISSUE THREAD

**Issue by ackoi** [paul-gauthier/aider#716] opened 2024-06-24 12:48 UTC
### Issue

I've found that the 3.5 Sonnet model is decent at continuing where it broke off.

Would it possible to implement this after hitting an output token limit?

Context:
Model claude-3-5-sonnet-20240620 has hit a
token limit!

Input tokens: 22664 of 200000
Output tokens: 3201 of 4096
Total tokens: 25865 of 200000

For more info:
https://aider.chat/docs/troubleshooting/toke
n-limits.html

**Comment by ackoi** [comment] 2024-06-24 13:23
Or is there something I'm missing as a way to use less tokens? Maybe not using SEARCH/REPLACE but some different way? I'm using it in the browser and not exactly sure how to configure this.

**Comment by Yona544** [comment] 2024-06-24 14:53
@ackoi Are you just prompting "Continue" and everything would be committed?

**Comment by ackoi** [comment] 2024-06-24 17:37
> @ackoi Are you just prompting "Continue" and everything would be committed?

That would be my requested features, yes. From my usage in the API Playground just asking it to continue after the 4000 output token cutoff works.

**Comment by paul-gauthier** [comment] 2024-06-24 20:39
This looks like a duplicate of #705, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-06-24 20:39 UTC
