### ISSUE TITLE
[BUG] Uncaught TypeError in core.pyx line 14

### ISSUE THREAD

**Issue by Emasoft** [paul-gauthier/aider#1707] opened 2024-09-24 17:52 UTC
Aider version: 0.57.1
Python version: 3.11.9
Platform: Linux-5.15.0-1068-aws-x86_64-with-glibc2.31
Python implementation: CPython
Virtual environment: No
OS: Linux 5.15.0-1068-aws (64bit)
Git version: git version 2.42.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 709, in main
    coder.run()
  File "base_coder.py", line 723, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 766, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1204, in send_message
    lint_errors = self.lint_edited(edited)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1298, in lint_edited
    errors = self.linter.lint(self.abs_root_path(fname))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "linter.py", line 112, in lint
    res += tree_context(rel_fname, code, lintres.lines)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "linter.py", line 228, in tree_context
    context = TreeContext(
              ^^^^^^^^^^^^
  File "grep_ast.py", line 47, in __init__
    parser = get_parser(lang)
             ^^^^^^^^^^^^^^^^
  File "core.pyx", line 19, in tree_sitter_languages.core.get_parser
  File "core.pyx", line 14, in tree_sitter_languages.core.get_language
TypeError: __init__() takes exactly 1 argument (2 given)

```

**Comment by fry69** [comment] 2024-09-24 17:59
Thanks for trying aider and filing this issue.

This looks like a duplicate of #1236. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by fry69** 2024-09-24 17:59 UTC
