### ISSUE TITLE
Uncaught ValueError in history.py line 120

### ISSUE THREAD

**Issue by StevenTCramer** [paul-gauthier/aider#1838] opened 2024-09-30 13:34 UTC
Aider version: 0.58.0
Python version: 3.11.4
Platform: Windows-10-10.0.22621-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.45.1.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 727, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1201, in send_message
    self.reply_completed()
  File "architect_coder.py", line 32, in reply_completed
    editor_coder = Coder.create(**new_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 132, in create
    done_messages = from_coder.summarizer.summarize_all(done_messages)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "history.py", line 120, in summarize_all
    raise ValueError("summarizer unexpectedly failed for all models")
ValueError: summarizer unexpectedly failed for all models

```

**Comment by fry69** [comment] 2024-09-30 13:38
Thank you for filing this issue.

Can you please post the first lines of aider with the models you used? That would really help.

Otherwise, this exception should be handled more gracefully, so I labeled it a bug for now.

**Comment by paul-gauthier** [comment] 2024-10-02 18:07
This looks like a duplicate of #1889. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-10-02 18:07 UTC
Labels: bug
