### ISSUE TITLE
Used deepseek-coder-v2 show Litellm error

### ISSUE THREAD

**Issue by ASHCBY** [paul-gauthier/aider#874] opened 2024-07-17 00:13 UTC
### Issue

Why I always show LiteLLM:ERROR: litellm_logging.py:1265 - Model=deepseek-coder-v2 not found in completion cost map. Setting 'response_cost' to None?

**Comment by paul-gauthier** [comment] 2024-07-17 13:35
Thanks for trying aider and filing this issue.

When reporting problems, it is very helpful if you can provide:

- Aider version
- LLM model you are using
- Any stack traces or error messages
- A description of what you were doing when the error happened. 

Including the “announcement” lines that aider prints at startup is an easy way to share some of this helpful info.

```
Aider v0.37.1-dev
Models: gpt-4o with diff edit format, weak model gpt-3.5-turbo
Git repo: .git with 243 files
Repo-map: using 1024 tokens
```

**Comment by ASHCBY** [comment] 2024-07-18 10:09
Aider v0.44.0
Model: ollama/deepseek-coder-v2 with whole edit format
Git repo: .git with 329 files
Repo-map: disabled
Use /help <question> for help, run "aider --help" to see cmd line args

When agent finished show this , and show: "Allow creation of new file game/main_game.py? y " and agent stop continue

**Comment by AlexJ-StL** [comment] 2024-07-19 15:42
After some work I got Groq/ Llama3-70b to work, which is normally not an issue. Then I got 1 prompt and response partially in before I got **"litellm.RateLimitError: RateLimitError: GroqException** - **Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-70b-8192` in organization `org_01ht7j91w5fjx8yabp2xh9hq37` on tokens per minute (TPM): Limit 6000, Used 0, Requested 7259. Please try again..."**

**Comment by paul-gauthier** [comment] 2024-07-22 07:07
This looks like a duplicate of #883, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-07-22 07:07 UTC
Labels: question
