### ISSUE TITLE
Uncaught TypeError in main.py line 172

### ISSUE THREAD

**Issue by tzkmx** [paul-gauthier/aider#1727] opened 2024-09-25 19:30 UTC
Aider version: <module 'aider.__version__' from 'C:\\Users\\Jesus\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\aider\\__version__.py'>
Python version: 3.12.6
Platform: Windows-11-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 11 (64bit)
Git version: git version 2.46.1.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 4, in <module>
    main()
  File "main.py", line 428, in main
    launch_gui(argv)
  File "main.py", line 172, in launch_gui
    if "-dev" in __version__:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'module' is not iterable

```

**Comment by fry69** [comment] 2024-09-25 19:52
Thank you for filing this issue.

This looks like an installation problem, please try to reinstall aider via official methods, see

-> https://aider.chat/docs/install/install.html <-

This document may also be helpful -> https://aider.chat/docs/troubleshooting/imports.html

**Comment by paul-gauthier** [comment] 2024-09-27 21:22
Thanks for trying aider and filing this issue.

This looks like a duplicate of #1502. Please see the comments there for more information, and feel free to continue the discussion within that issue.

I'm going to close this issue for now. But please let me know if you think this is actually a distinct issue and I will reopen this issue.

**Closed by paul-gauthier** 2024-09-27 21:22 UTC
Labels: question
