### ISSUE TITLE
Possible benefits of using OpenAIs 'Assistants' API 

### ISSUE THREAD

**Issue by tastyblob** [paul-gauthier/aider#548] opened 2024-04-11 21:08 UTC
Discussion ticket.
Without having satisfiably researched or tested the OpenAI assistants API described here: https://platform.openai.com/docs/assistants/overview?context=with-streaming, I'm interested wether adding a compatible aider Coder based on features provided by incorporating use of Assistants could yield improvements in session handling, context specificity and maybe prompt management- for example in cases where aider sessions target the same repository context but are spaced apart over multiple, non-continuous invocations of aider. 

Possible benefits should likely be measured against the current file-based history- and context handling of aider session using .aider*-dotfiles, as well as downstream improvements of any difficulty the current file based approach may pose (not that I'm aware of any).

Input on practical potential and viability within aider are appreciated.  

```
Aider v0.21.2-dev
Model: gpt-4-0613 using diff edit format
Git repo: .git with 134 files
Repo-map: using 1024 tokens
Use /help to see in-chat commands, run with --help to see cmd line args
```

**Comment by paul-gauthier** [comment] 2024-04-11 21:59
This looks like a duplicate of #349, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-04-11 21:59 UTC
Labels: question
