### ISSUE TITLE
Renaming/moving files

### ISSUE THREAD

**Issue by memaxo** [paul-gauthier/aider#651] opened 2024-06-07 04:05 UTC
### Issue

Have you thought about giving aider the ability to rename and move files to different parts of the subdirectory? 

When asking aider to suggest improvements to my repo, it suggested that I move files into subdirectories. Because these files are long, I needed to move them manually and then change imports/references across the code base. Its a minor feature but I think it would be useful!

P.S. Thank you Paul for developing this. Aider has become my primary modality for code editing now!

**Comment by paul-gauthier** [comment] 2024-06-10 22:28
Thanks for trying aider and filing this issue. This looks like a duplicate of #528, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-06-10 22:28 UTC
