### ISSUE TITLE
[FeatReq] A better mapping of the project should be provided to the AI since it does not recognize sub projects.

### ISSUE THREAD

**Issue by Emasoft** [paul-gauthier/aider#947] opened 2024-07-27 17:47 UTC
### Issue

A better mapping of the project should be provided to the AI since it does not recognize sub projects.
Very often a project is actually divided in many parts to be easier to develop. This means that it is common for a project root to contain sub folders with other projects developed concurrently as separate modules. And the git repo of the main project is often different from the git repo of those sub projects. 
Unfortunately Aider does not map the root project as separate from the other projects in the sub folders, nor detects (or create) different git repos for each of them. This causes a lot of trouble. For example different projects have separate requirements, setup and toml files, but Aider apply changes to all of them without criteria, sometimes duplicating or erasing parts of those files. The result is that Aider breaks those projects configurations files, making multipart projects development impossible.
Please add support for multipart projects, with automatic detection of additional sub-projects in the subdirectories.
Thanks.

**Comment by paul-gauthier** [comment] 2024-07-28 11:01
This looks like a duplicate of #339, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-07-28 11:01 UTC
