### ISSUE TITLE
Trouble distinguishing between instructions, filenames & content

### ISSUE THREAD

**Issue by mgisch** [paul-gauthier/aider#128] opened 2023-07-19 07:00 UTC
Thank you for previously looking into issue#73 for me (I couldn't re-open that one).

I tried a much more complex example, running aider v0.9.0. The code that the AI response produced on console looked promising however aider was not able to distinguish between code content, instructions for what it's doing and suggested file names to be created. The full console session is quite long but this is the prompt I gave it (model 3.5):

```
create a fastapi application split into multiple files using MVC concepts. The application enables a User to register an account by 
providing an email and password. User account details are saved to an sqlite database. Existing users can log in using their email and password. After successful login they see a basic greeting page. Create the front end UI using the react framework.
```
At conclusion it asked me:
```
Allow creation of new file 1. Create a new directory for your project and navigate into it:? n
Skipping edit to 1. Create a new directory for your project and navigate into it:
Allow creation of new file 2. Initialize a new Python virtual environment:? n
Skipping edit to 2. Initialize a new Python virtual environment:
Allow creation of new file 3. Activate the virtual environment:? n
Skipping edit to 3. Activate the virtual environment:
Allow creation of new file 4. Install the required dependencies:? n
Skipping edit to 4. Install the required dependencies:
Allow creation of new file 5. Create the following directory structure:? y
Add 5. Create the following directory structure: to git? n
Allow creation of new file 6. Create a new file `app/__init__.py` with the following content:? y
Add 6. Create a new file `app/__init__.py` with the following content: to git? yy
Allow creation of new file 7. Create a new file `app/models.py` with the following content:? y
Add 7. Create a new file `app/models.py` with the following content: to git? y
Allow creation of new file 8. Create a new file `app/schemas.py` with the following content:? y
Add 8. Create a new file `app/schemas.py` with the following content: to git? y
Allow creation of new file 10. Create a new file `app/controllers/auth.py` with the following content:? y
Add 10. Create a new file `app/controllers/auth.py` with the following content: to git? y
Allow creation of new file 11. Create a new file `app/controllers/user.py` with the following content:? y
Add 11. Create a new file `app/controllers/user.py` with the following content: to git? y
Allow creation of new file 12. Create a new file `app/main.py` with the following content:? y
Add 12. Create a new file `app/main.py` with the following content: to git? y
Allow creation of new file 13. Create a new file `main.py` with the following content:? y
Add 13. Create a new file `main.py` with the following content: to git? y
Allow creation of new file 15. To run the FastAPI application, execute the following command:? n
Skipping edit to 15. To run the FastAPI application, execute the following command:
Applied edit to 10. Create a new file `app/controllers/auth.py` with the following content:
Applied edit to 11. Create a new file `app/controllers/user.py` with the following content:
Applied edit to 12. Create a new file `app/main.py` with the following content:
Applied edit to 13. Create a new file `main.py` with the following content:
Applied edit to 5. Create the following directory structure:
Applied edit to 6. Create a new file `app/__init__.py` with the following content:
Applied edit to 7. Create a new file `app/models.py` with the following content:
Applied edit to 8. Create a new file `app/schemas.py` with the following content:
Commit 3514113 aider: Refactor user registration and login routes to separate controller files.
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────10. Create a new file `app/controllers/auth.py` with the following content: 11. Create a new file `app/controllers/user.py` with the f>
```
And consequently it ends up with this resulting directory tree:
```
✔ ~/dev/gpt/app2 [master L|✔] 
16:49 $ ls -lR
.:
total 32
drwxr-xr-x 3 martin martin 4096 Jul 19 16:49 '10. Create a new file `app'
drwxr-xr-x 3 martin martin 4096 Jul 19 16:49 '11. Create a new file `app'
drwxr-xr-x 2 martin martin 4096 Jul 19 16:49 '12. Create a new file `app'
-rw-r--r-- 1 martin martin  490 Jul 19 16:49 '13. Create a new file `main.py` with the following content:'      
-rw-r--r-- 1 martin martin  271 Jul 19 16:48 '5. Create the following directory structure:'
drwxr-xr-x 2 martin martin 4096 Jul 19 16:48 '6. Create a new file `app'
drwxr-xr-x 2 martin martin 4096 Jul 19 16:49 '7. Create a new file `app'
drwxr-xr-x 2 martin martin 4096 Jul 19 16:49 '8. Create a new file `app'

'./10. Create a new file `app':
total 4
drwxr-xr-x 2 martin martin 4096 Jul 19 16:49 controllers

'./10. Create a new file `app/controllers':
total 4
-rw-r--r-- 1 martin martin 750 Jul 19 16:49 'auth.py` with the following content:'

'./11. Create a new file `app':
total 4
drwxr-xr-x 2 martin martin 4096 Jul 19 16:49 controllers

'./11. Create a new file `app/controllers':
total 4
-rw-r--r-- 1 martin martin 372 Jul 19 16:49 'user.py` with the following content:'

'./12. Create a new file `app':
total 4
-rw-r--r-- 1 martin martin 412 Jul 19 16:49 'main.py` with the following content:'

'./6. Create a new file `app':
total 4
-rw-r--r-- 1 martin martin 490 Jul 19 16:49 '__init__.py` with the following content:'

'./7. Create a new file `app':
total 4
-rw-r--r-- 1 martin martin 262 Jul 19 16:49 'models.py` with the following content:'

'./8. Create a new file `app':
total 4
-rw-r--r-- 1 martin martin 156 Jul 19 16:49 'schemas.py` with the following content:'
✔ ~/dev/gpt/app2 [master L|✔] 
16:49 $ cat 10.\ Create\ a\ new\ file\ \`app/controllers/auth.py\`\ with\ the\ following\ content\: 
from fastapi import APIRouter, Depends
from fastapi.security import OAuth2PasswordBearer, OAuth2PasswordRequestForm
from app.models import User
from app.schemas import UserCreate, UserLogin
from app.database import get_db
from app.utils import create_access_token

router = APIRouter()

oauth2_scheme = OAuth2PasswordBearer(tokenUrl="auth/login")

@router.post("/register")
async def register(user: UserCreate, db=Depends(get_db)):
    # Create a new user in the database
    # Hash the password before saving it
    # Return the created user
    pass

@router.post("/login")
async def login(form_data: OAuth2PasswordRequestForm = Depends(), db=Depends(get_db)):
    # Verify the user's credentials
    # Generate and return an access token
    pass
✔ ~/dev/gpt/app2 [master L|✔] 
```

**Comment by paul-gauthier** [comment] 2023-07-19 12:04
Thanks for trying aider and reporting this issue.

I think the root cause is that you're asking too much from GPT-3.5. Asking it to create a multi-file application with a bunch of specific details all in one go is going to be too much for it.

The [tips section on the homepage](https://aider.chat/#tips) recommends: *Large changes are best performed as a sequence of thoughtful bite sized steps, where you plan out the approach and overall design. Walk GPT through changes like you might with a junior dev. Ask for a refactor to prepare, then ask for the actual change. Spend the time to ask for code quality/structure improvements.*

That sort of step-by-step coding is critical for GPT-3.5.

If you have access to GPT-4, I think you would have much better results.

**Comment by mgisch** [comment] 2023-07-19 21:58
Thanks Paul; I don't yet have access to gpt-4 api unfortunately...on wait list.
I havn't actually tried the code this over-ambitious prompt produced, it just looked like this could be an issue with how aider parses the response output but understand if the focus is on improving working with gpt-4 at this point.
These are just experiments to figure out where the limits are.
Thanks for taking a look.

**Comment by paul-gauthier** [comment] 2023-07-20 16:18
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Closed** 2023-07-21 10:03 UTC
Labels: question
