### ISSUE TITLE
Zed extension

### ISSUE THREAD

**Issue by techydad05** [paul-gauthier/aider#1454] opened 2024-09-09 17:04 UTC
### Issue

Im wondering if its possible to create a Zed.dev  extension?

### Version and model info

Aider 0.55

**Comment by paul-gauthier** [comment] 2024-09-09 21:13
This looks like a duplicate of #851 so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-09-09 21:13 UTC
