### ISSUE TITLE
Invalid literal for int() with base 10: ':1'

### ISSUE THREAD

**Issue by AllenDang** [paul-gauthier/aider#550] opened 2024-04-12 03:20 UTC
When asking questions or reporting issues, it is very helpful if you can include:

- Aider version (python -m pip install git+https://github.com/paul-gauthier/aider.git@main)

The easiest way to do this is just just copy & paste the announcement lines that aider prints when you launch it, like these:

```
Aider v0.28.1-dev
Add .aider* to .gitignore (recommended)? y
Added .aider* to .gitignore
Traceback (most recent call last):
  File "/Users/allen/.virtualenvs/venv_aider/lib/python3.11/site-packages/httpx/_urlparse.py", line 346, in normalize_port
    port_as_int = int(port)
                  ^^^^^^^^^
ValueError: invalid literal for int() with base 10: ':1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/allen/.virtualenvs/venv_aider/bin/aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/allen/.virtualenvs/venv_aider/lib/python3.11/site-packages/aider/main.py", line 590, in main
    client = openai.OpenAI(api_key=args.openai_api_key, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/allen/.virtualenvs/venv_aider/lib/python3.11/site-packages/openai/_client.py", line 106, in __init__
    super().__init__(
  File "/Users/allen/.virtualenvs/venv_aider/lib/python3.11/site-packages/openai/_base_client.py", line 758, in __init__
    self._client = http_client or SyncHttpxClientWrapper(
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/allen/.virtualenvs/venv_aider/lib/python3.11/site-packages/httpx/_client.py", line 696, in __init__
    self._mounts: typing.Dict[URLPattern, typing.Optional[BaseTransport]] = {
                                                                            ^
  File "/Users/allen/.virtualenvs/venv_aider/lib/python3.11/site-packages/httpx/_client.py", line 697, in <dictcomp>
    URLPattern(key): None
    ^^^^^^^^^^^^^^^
  File "/Users/allen/.virtualenvs/venv_aider/lib/python3.11/site-packages/httpx/_utils.py", line 370, in __init__
    url = URL(pattern)
          ^^^^^^^^^^^^
  File "/Users/allen/.virtualenvs/venv_aider/lib/python3.11/site-packages/httpx/_urls.py", line 115, in __init__
    self._uri_reference = urlparse(url, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/allen/.virtualenvs/venv_aider/lib/python3.11/site-packages/httpx/_urlparse.py", line 246, in urlparse
    parsed_port: typing.Optional[int] = normalize_port(port, scheme)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/allen/.virtualenvs/venv_aider/lib/python3.11/site-packages/httpx/_urlparse.py", line 348, in normalize_port
    raise InvalidURL(f"Invalid port: {port!r}")
httpx.InvalidURL: Invalid port: ':1'
```

I can make sure the valid open api key is set as ENV variable.

**Comment by paul-gauthier** [comment] 2024-04-12 15:21
Thanks for trying aider and filing this issue.

It looks like you may have provided an invalid URL for the `--openai-api-base` argument. What URL are you using?

You can run `aider --verbose` to show all the active switches/configs.

**Comment by AllenDang** [comment] 2024-04-15 02:33
@paul-gauthier It's the first time I heard I need to pass URL of open ai, it is not mentioned in the installation instruction, may be update the document?

I followed the doc, it only shows me to pass the API key.

<img width="871" alt="image" src="https://github.com/paul-gauthier/aider/assets/18550/b68d8b14-544d-4f3c-9c99-958f2574f867">

**Comment by paul-gauthier** [comment] 2024-04-15 19:57
Again, can you share the output of `aider --verbose` so I can see what switches/configs are active. Something seems to be specifying an invalid api base url.

**Comment by AllenDang** [comment] 2024-04-16 02:31
@paul-gauthier Here it is
```
❯ aider --verbose
Aider v0.28.1-dev
Command Line Args:   --verbose
Environment Variables:
  OPENAI_API_KEY:    ***
Defaults:
  --model:           gpt-4-1106-preview
  --skip-model-availability-check:False
  --voice-language:  en
  --map-tokens:      1024
  --input-history-file:/Users/allen/Documents/Gocode/src/tripo-dc-bot/.aider.input.history
  --chat-history-file:/Users/allen/Documents/Gocode/src/tripo-dc-bot/.aider.chat.history.md
  --user-input-color:#00cc00
  --tool-error-color:#FF2222
  --assistant-output-color:#0088ff
  --code-theme:      default
  --aiderignore:     /Users/allen/Documents/Gocode/src/tripo-dc-bot/.aiderignore
  --encoding:        utf-8

Option settings:
  - aiderignore: /Users/allen/Documents/Gocode/src/tripo-dc-bot/.aiderignore
  - apply: None
  - assistant_output_color: #0088ff
  - auto_commits: True
  - chat_history_file: /Users/allen/Documents/Gocode/src/tripo-dc-bot/.aider.chat.history.md
  - check_update: False
  - code_theme: default
  - commit: False
  - config: None
  - dark_mode: False
  - dirty_commits: True
  - dry_run: False
  - edit_format: None
  - encoding: utf-8
  - files: []
  - git: True
  - gitignore: True
  - input_history_file: /Users/allen/Documents/Gocode/src/tripo-dc-bot/.aider.input.history
  - light_mode: False
  - map_tokens: 1024
  - message: None
  - message_file: None
  - model: gpt-4-1106-preview
  - openai_api_base: None
  - openai_api_deployment_id: None
  - openai_api_key: ***
  - openai_api_type: None
  - openai_api_version: None
  - openai_organization_id: None
  - pretty: True
  - show_diffs: False
  - show_repo_map: False
  - skip_check_update: False
  - skip_model_availability_check: False
  - stream: True
  - tool_error_color: #FF2222
  - tool_output_color: None
  - user_input_color: #00cc00
  - verbose: True
  - voice_language: en
  - yes: None
```

**Comment by paul-gauthier** [comment] 2024-04-17 16:52
Did aider throw the `httpx.InvalidURL: Invalid port: ':1'` error when you ran it with `aider --verbose`? Because I don't see anything in the verbose output that would explain such an error.

**Comment by AllenDang** [comment] 2024-04-18 09:52
@paul-gauthier 
![image](https://github.com/paul-gauthier/aider/assets/18550/7e2cbe49-f1a4-4c9c-b623-bec66913545b)

**Comment by iusedmyimagination** [comment] 2024-04-18 10:51
Try `pip install -U aider-chat` instead, `aider` is another project.

**Comment by AllenDang** [comment] 2024-04-18 12:18
@paul-gauthier 
```
❯ aider --verbose
Aider v0.28.0
Command Line Args:   --verbose
Environment Variables:
  OPENAI_API_KEY:    ***
Defaults:
  --model:           gpt-4-1106-preview
  --skip-model-availability-check:False
  --voice-language:  en
  --map-tokens:      1024
  --input-history-file:/Users/allen/Documents/Gocode/src/tripo-blog-bot/.aider.input.history
  --chat-history-file:/Users/allen/Documents/Gocode/src/tripo-blog-bot/.aider.chat.history.md
  --user-input-color:#00cc00
  --tool-error-color:#FF2222
  --assistant-output-color:#0088ff
  --code-theme:      default
  --aiderignore:     /Users/allen/Documents/Gocode/src/tripo-blog-bot/.aiderignore
  --encoding:        utf-8

Option settings:
  - aiderignore: /Users/allen/Documents/Gocode/src/tripo-blog-bot/.aiderignore
  - apply: None
  - assistant_output_color: #0088ff
  - auto_commits: True
  - chat_history_file: /Users/allen/Documents/Gocode/src/tripo-blog-bot/.aider.chat.history.md
  - check_update: False
  - code_theme: default
  - commit: False
  - config: None
  - dark_mode: False
  - dirty_commits: True
  - dry_run: False
  - edit_format: None
  - encoding: utf-8
  - files: []
  - git: True
  - gitignore: True
  - input_history_file: /Users/allen/Documents/Gocode/src/tripo-blog-bot/.aider.input.history
  - light_mode: False
  - map_tokens: 1024
  - message: None
  - message_file: None
  - model: gpt-4-1106-preview
  - openai_api_base: None
  - openai_api_deployment_id: None
  - openai_api_key: ***
  - openai_api_type: None
  - openai_api_version: None
  - openai_organization_id: None
  - pretty: True
  - show_diffs: False
  - show_repo_map: False
  - skip_check_update: False
  - skip_model_availability_check: False
  - stream: True
  - tool_error_color: #FF2222
  - tool_output_color: None
  - user_input_color: #00cc00
  - verbose: True
  - voice_language: en
  - yes: None
Traceback (most recent call last):
  File "/Users/allen/.virtualenvs/venv_aider/lib/python3.11/site-packages/httpx/_urlparse.py", line 346, in normalize_port
    port_as_int = int(port)
                  ^^^^^^^^^
ValueError: invalid literal for int() with base 10: ':1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/allen/.virtualenvs/venv_aider/bin/aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/allen/.virtualenvs/venv_aider/lib/python3.11/site-packages/aider/main.py", line 590, in main
    client = openai.OpenAI(api_key=args.openai_api_key, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/allen/.virtualenvs/venv_aider/lib/python3.11/site-packages/openai/_client.py", line 106, in __init__
    super().__init__(
  File "/Users/allen/.virtualenvs/venv_aider/lib/python3.11/site-packages/openai/_base_client.py", line 758, in __init__
    self._client = http_client or SyncHttpxClientWrapper(
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/allen/.virtualenvs/venv_aider/lib/python3.11/site-packages/httpx/_client.py", line 696, in __init__
    self._mounts: typing.Dict[URLPattern, typing.Optional[BaseTransport]] = {
                                                                            ^
  File "/Users/allen/.virtualenvs/venv_aider/lib/python3.11/site-packages/httpx/_client.py", line 697, in <dictcomp>
    URLPattern(key): None
    ^^^^^^^^^^^^^^^
  File "/Users/allen/.virtualenvs/venv_aider/lib/python3.11/site-packages/httpx/_utils.py", line 370, in __init__
    url = URL(pattern)
          ^^^^^^^^^^^^
  File "/Users/allen/.virtualenvs/venv_aider/lib/python3.11/site-packages/httpx/_urls.py", line 115, in __init__
    self._uri_reference = urlparse(url, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/allen/.virtualenvs/venv_aider/lib/python3.11/site-packages/httpx/_urlparse.py", line 246, in urlparse
    parsed_port: typing.Optional[int] = normalize_port(port, scheme)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/allen/.virtualenvs/venv_aider/lib/python3.11/site-packages/httpx/_urlparse.py", line 348, in normalize_port
    raise InvalidURL(f"Invalid port: {port!r}")
httpx.InvalidURL: Invalid port: ':1'
```

**Comment by paul-gauthier** [comment] 2024-04-21 22:22
You might want to try upgrading to the new v0.29.0 and see if this problem resolves.

**Comment by AllenDang** [comment] 2024-04-22 02:47
@paul-gauthier 
![image](https://github.com/paul-gauthier/aider/assets/18550/832e4679-421c-49fb-84db-b556ebc87e2f)

**Comment by paul-gauthier** [comment] 2024-04-29 20:13
I am unable to reproduce this bug anywhere. But it appears that this might be an issue with the `httpx` library that `openai-python` uses.

https://github.com/openai/openai-python/issues/1054

That issue suggests that downgrading httpx to 0.23.3 solves the problem. Want to try doing this and see if it helps?

```
pip install httpx==0.23.3
```

**Comment by paul-gauthier** [comment] 2024-05-05 13:23
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Closed by paul-gauthier** 2024-05-05 13:23 UTC
Labels: question
