### ISSUE TITLE
Uncaught TypeError in symbolic.py line 413

### ISSUE THREAD

**Issue by vinciblu** [paul-gauthier/aider#1601] opened 2024-09-19 19:44 UTC
Aider version: 0.56.0
Python version: 3.10.2
Platform: macOS-14.5-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.5.0 (64bit)
Git version: git version 2.42.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 4, in <module>
    main()
  File "main.py", line 698, in main
    coder.run()
  File "base_coder.py", line 735, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 772, in run_one
    message = self.preproc_user_input(user_message)
  File "base_coder.py", line 761, in preproc_user_input
    return self.commands.run(inp)
  File "commands.py", line 221, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
  File "commands.py", line 196, in do_run
    return cmd_method(args)
  File "commands.py", line 432, in cmd_undo
    self.raw_cmd_undo(args)
  File "commands.py", line 483, in raw_cmd_undo
    current_branch = self.coder.repo.repo.active_branch.name
  File "base.py", line 1036, in active_branch
    return self.head.reference
  File "symbolic.py", line 413, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to '215b3733506b87ef20d878b697c74c6b3f7b7e8b'

```

**Comment by fry69** [comment] 2024-09-19 19:51
Thank you for filing this issue.

Unfortunately GitPython (which aider uses) really does not like a git repository in detached head state (checkout without being on a branch). For now I'd recommend to avoid this and start aider only when your git repository is on a branch.

**Comment by vinciblu** [comment] 2024-09-19 20:03
ohh okay thank you.

**Comment by paul-gauthier** [comment] 2024-09-20 18:42
This looks like a duplicate of #1506, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-09-20 18:42 UTC
