### ISSUE TITLE
Needs slightly tweaked edit format for adding text?

### ISSUE THREAD

**Issue by mikehearn** [paul-gauthier/aider#340] opened 2023-11-10 15:53 UTC
gpt-4-preview seems to like this sort of thing, which obviously doesn't work, but it's fair enough because I'm not sure how I'd express appends with this format either?

```
 headlines.css
 <<<<<<< SEARCH
 /* No changes in this part of the file */
 =======
 /* Add the following CSS rules for the .number class */
 .number {
     display: inline-block;
     width: 30px; /* Adjust the width as needed */
     margin-left: -40px; /* Adjust the negative margin to offset the number to the left */
     text-align: right;
     color: black;
     font-family: 'Noto Serif Display', serif;
 }
 >>>>>>> REPLACE
```

**Comment by paul-gauthier** [comment] 2023-11-14 19:50
Duplicate of #343.

**Closed by paul-gauthier** 2023-11-14 19:50 UTC
