### ISSUE TITLE
Question: did you use `aider-chat` with Gemini 1.5 for a large codebase

### ISSUE THREAD

**Issue by younes-io** [paul-gauthier/aider#485] opened 2024-02-22 12:53 UTC
I came across this interesting [Reddit post](https://www.reddit.com/r/singularity/comments/1atjz9v/ive_put_a_complex_codebase_into_a_single/) and it just made me thinking if any of you tested Gemini 1.5 with a large codebase using `aider-chat`?
I don't have access yet to Gemini 1.5

**Comment by paul-gauthier** [comment] 2024-02-24 15:31
Thanks for trying aider and filing this issue.

I'm not aware that anyone has tried aider with the new Gemini models yet. 

There's a FAQ entry that might contain helpful information:

https://aider.chat/docs/faq.html#can-i-use-aider-with-other-llms-local-llms-etc

**Comment by younes-io** [comment] 2024-02-28 07:33
> The huge context size would definitely be a killer thing to have... Ofc if Gemini 1.5 is good at these things at all (heard mixed reviews tbh)

Absolutely, I'm based in Europe and it's not available yet; that's why I was thinking it would be interesting to see if someone hopefully tried this :D

**Comment by paul-gauthier** [comment] 2024-02-28 20:57
This looks like a duplicate of #172, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Closed by paul-gauthier** 2024-02-28 20:57 UTC
Labels: question

**Comment by NightMachinery** [comment] 2024-04-11 01:43
@paul-gauthier  Gemini Pro 1.5 is now available on OpenRouter.
